### ISSUE TITLE
Is Orange-Boosted-Bootstrap RTL compatible ?

### ISSUE THREAD

**Issue by RomainTrebuchon** [Orange-OpenSource/Orange-Boosted-Bootstrap#10]
Hello, we use bootstrap-rtl library for arabic site version and we want to know if your components like the stepBar and others are compatible.

**Comment by Lausselloic** [comment]
Hello,

Yes Boosted v4 or upper is available in RTL (dist/css/boosted-rtl.css) You can see a sample of the use here : http://boosted.orange.com/v4-alpha/examples/rtl-orange-form/
