### ISSUE TITLE
3-way toggle not workin'

### ISSUE THREAD

**Issue by Aniort** [Orange-OpenSource/Orange-Boosted-Bootstrap#100]
when using the 3-way toggle button, it's impossible to check programmatically the 2d and third ways even if visually it seems to be checked but they aren't. This true when you are using keyboard navigation (space bar) to check.

**Comment by liyokuna** [comment]
Hello,
After some [reviews](https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/radio), the check can be seen as default value. It convenient to let devs using it and change the state.

**Comment by liyokuna** [comment]
@StreiffBerenice what do you think ?

**Comment by StreiffBerenice** [comment]
I need a screenshot please to understand what are you talking about ! Thanks

**Comment by liyokuna** [comment]
@StreiffBerenice,
We are talking about the [3 way toggle](https://boosted.netlify.com/docs/4.3/boostwatch/#switches).
When ![inspecting](https://user-images.githubusercontent.com/11217936/54447916-d3ea2400-474a-11e9-9d0e-ae563b029d54.PNG) the element, you can see that the checked is not set as you click on a value of the toggle.
I was saying above that that normal as that component is a showcase.
you cans see that on other showcases.
![3waytoggle](https://user-images.githubusercontent.com/11217936/54447869-b9b04600-474a-11e9-90c5-e0f90029f55c.PNG)

**Comment by Lausselloic** [comment]
@Aniort I can confirm there's something going wrong when browsing with keyboard. It's related to the button plugin. An [issue had been open](https://github.com/twbs/bootstrap/issues/28564) we could fix it in boosted by the way

**Comment by Lausselloic** [comment]
@Aniort could you please check the latest version and close this issue if it's good for you? I've port back the fix from Bootstrap PR : 
https://deploy-preview-133--boosted.netlify.com/docs/4.3/components/buttons/#checkbox-and-radio-buttons

**Comment by Aniort** [comment]
I check this new release of the 3 ways toggle button.
It's now usable but the only thing not ok is that the focus is invisible, so improve the effect visibility on focus.

**Comment by Lausselloic** [comment]
see PR #137 focus is now handled on input element and on the label one

**Comment by Aniort** [comment]
Evaluation of the 3 kinds of 3-ways tog'gles 
ok for me !
can be merged !
