### ISSUE TITLE
Documentation footer is not sticky

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1008]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On a big screen, when we go to "Design guidelines", the footer is not sicky and is display at around 3/4 of the screen.

![Screenshot from 2021-12-30 07-50-45](https://user-images.githubusercontent.com/17381666/147728467-55d165e1-625b-460e-b517-898826dd1944.png)

### Reduced test cases

At the time of writing this, it can only be seen locally at http://localhost:9001/docs/5.1/guidelines/ since it will be deployed with the 5.2.0 version of Boosted.

Maybe worth a try: [A Clever Sticky Footer Technique](https://css-tricks.com/a-clever-sticky-footer-technique/).

Note: even if we don't see it in Bootstrap since there is not short pages there, this issue exists as well.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

v5.2.0 (current _main_ branch)

**Comment by MewenLeHo** [comment]
@julien-deramond: IMO the footer is fine, the problem on this page could be related to: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/765
