### ISSUE TITLE
Consider using font-display

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#102]
And I'd recommend the `swap` value for Helvetica, but maybe a `block` value for icon-font (since no fallback font will be appropriate).

- [MDN documentation about `font-display`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display)
- And [a very comprehensive guide by Monica Dinculescu](https://font-display.glitch.me/)

**Comment by Lausselloic** [comment]
yes I will add it to the next release, I need to update npm package the one of 4.2.1 is buggy

**Comment by Lausselloic** [comment]
Added in that commit : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/db698cee70d9ba266fe104843ccae7ac2330d9e2
