### ISSUE TITLE
[RTL] — Breadcrumb arrows  in wrong direction

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#103]
Making them `rotate(180deg)` and adjusting paddings seems to do the job.

**Comment by Lausselloic** [comment]
fixed by [commit](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/7b6629d8b451fc380895afdf809d5a87615c2386)

a global test will be done on all element by testing documentation in rtl mode

**Comment by Lausselloic** [comment]
a new boostwatch page have been added for rtl checking : https://boosted.netlify.com/docs/4.3/boostwatch/rtl-index.html
