### ISSUE TITLE
Outline not visible on iOS and Safari on Star Rating

### ISSUE THREAD

**Issue by louismaximepiton** [Orange-OpenSource/Orange-Boosted-Bootstrap#1035]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The outline for focus-visible isn't there for iOS and Mac. Maybe search for tabindex="0" or for options in MacOS directly.

### Reduced test cases

Go to [link](https://deploy-preview-887--boosted.netlify.app/docs/5.1/forms/checks-radios/#star-rating) and click on stars (or touch).

### What operating system(s) and browser(s) are you seeing the problem on?

(Source Browserstack)
* macOS + Safari
* iOS - Chrome

### What version of Boosted are you using?

_main_ branch (5.2.0)

**Comment by MewenLeHo** [comment]
@louismaximepiton: we may try https://www.tempertemper.net/blog/refining-focus-styles-with-focus-visible

**Comment by isabellechanclou** [comment]
On macOS + Safari, to be able to see focuses, you need to go to Safari/Preferences and tick the Accessibility parameter "Press Tab to highlight each item on a webpage". It seems there is nothing to add in the code.

Didn't test iOS - Chrome so far.

**Comment by louismaximepiton** [comment]
Closed by #1437
