### ISSUE TITLE
ODS > Footers

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/Orange-Boosted-Bootstrap#1045]
## Requirement

**For** a Developer 
**Who** is creating an Orange Website
**The** Footers Integration
**is a** automated component
**that** proposes the web site's Orange footers  
**unlike** the default bootstrap framework
**Boosted** will provide this ready to use component compatible with the Orange Design and the accessibility requirements

## Description

Footer module is a combination of different sub-elements that can compose a footer:
* Terms & Conditions
* Navigation
* Follow us bar
* Email sign up
* Service links

## References

Orange Design System: [Modules > Footer
](https://system.design.orange.com/0c1af118d/p/20e9fb-footer/b/9571c3)

## Implementation

- [x] #892

**Comment by louismaximepiton** [comment]
Should be closed right ?
