### ISSUE TITLE
ODS > Cards

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/Orange-Boosted-Bootstrap#1050]
## Requirement

**For** a Developer 
**Who** is creating an Orange Website
**The** Cards Integration
**is an** automated component
**that** proposes the web site's Orange Cards components
**unlike** the default bootstrap framework
**Boosted** will provide this ready to use component compatible with the Orange Design and the accessibility requirements

## Description

Users can build a cards into the website with all the following:

* Card Size (Large / Medium / Small)
* Black Card with Title
* Black Card with Title & Metadata
* Black Card with Title & Caption
* Black Card with Title, Caption & Metadata
* Black Card with Title, Caption & Action Icons
* Black Card with Title, Caption & Button
* White Card & Gray Outline with Title
* White Card & Gray Outline with Title & Metadata
* White Card & Gray Outline with Title & Caption
* White Card & Gray Outline with Title, Caption & Metadata
* White Card & Gray Outline with Title, Caption & Action Icons
* White Card & Gray Outline with Title, Caption & Button
* White Card with Title
* White Card with Title & Metadata
* White Card with Title & Caption
* White Card with Title, Caption & Metadata
* White Card with Title, Caption & Action Icons
* White Card with Title, Caption & Button
* Light & Dark mode support

## References

Orange Design System: [Modules > Cards
](https://system.design.orange.com/0c1af118d/p/82eaf1-cards/b/69655e)

## Implementation

- [ ] #980 
- [ ] ??
- [ ] ??
- [ ] ??

**Comment by julien-deramond** [comment]
All cards are implemented, this one can be closed.
