### ISSUE TITLE
[Boosted vs Brand stencils] large input height

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#106]
46px height in Boosted / 50px height in stencil

Stencil
![image](https://user-images.githubusercontent.com/13221271/51984260-3210bf80-249b-11e9-8447-383bc48d910b.png)

Boosted
![image](https://user-images.githubusercontent.com/13221271/51984269-363cdd00-249b-11e9-8037-f7f14a8cf93c.png)

**Comment by Lausselloic** [comment]
fixed by commit : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/431fb605a077fc515937989b664cfd29347b64f9
