### ISSUE TITLE
[Boosted vs Brand stencils] input border color

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#107]
Input border color is different : 

Stencil
![image](https://user-images.githubusercontent.com/13221271/51984612-1823ac80-249c-11e9-958a-aad79d4474d8.png)

Boosted 
![image](https://user-images.githubusercontent.com/13221271/51984628-1bb73380-249c-11e9-8d25-d71422a37b49.png)

**Comment by Lausselloic** [comment]
fixed by commit : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/fb593ac5ca5be408d2ae749b38ee04f380d2bcf5
