### ISSUE TITLE
Label for switch is not vertically aligned

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#1072]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://boosted.orange.com/docs/5.1/forms/checks-radios/#switches
Label is not well aligned
![image](https://user-images.githubusercontent.com/11272238/151811907-191fe67c-6419-453a-ab5a-9a6135bdbff6.png)

### Reduced test cases

https://boosted.orange.com/docs/5.1/forms/checks-radios/#switches

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

91.2.0 ESR

**Comment by Lausselloic** [comment]
![image](https://user-images.githubusercontent.com/11272238/151811987-24b4bc88-2cbc-415a-b1bb-5684d17d12f6.png)
Jumping padding-top for 
.form-switch .form-check-label to 0.413rem could do the job?

Need a Design validation

**Comment by julien-deramond** [comment]
Thanks for the issue!

> Jumping padding-top for .form-switch .form-check-label to 0.413rem could do the job?

Yes, it seems to do the job. I noticed that the labels are misaligned as well for the "classic" checkboxes and radios.

> Need a Design validation

Yes we'll ask a design review at the end of the PR.
