### ISSUE TITLE
[Boosted vs Brand stencils] input text weight

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#108]
Stencil
![image](https://user-images.githubusercontent.com/13221271/51984747-5a4cee00-249c-11e9-8185-4211712ab946.png)

Boosted 
![image](https://user-images.githubusercontent.com/13221271/51984750-5de07500-249c-11e9-924c-ee7de38c1cd1.png)

**Comment by Lausselloic** [comment]
fixed by commit : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/fb593ac5ca5be408d2ae749b38ee04f380d2bcf5
