### ISSUE TITLE
ODS > Navigation > Carousel Navigation

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/Orange-Boosted-Bootstrap#1084]
# Carousel Navigation

## Requirement

**For** a developer
**Who** is creating an Orange website
**The** carousel navigation
**is a** component
**that** allows to manipulate a carousel
**Boosted** will provide this ready to use component compatible with Orange design specifications and a11y requirements

[DSM reference](https://system.design.orange.com/0c1af118d/p/7773e1-carousel-navigation/b/99a7b7)

## General description

Carousel navigation allows users to navigate forward and backwards through content in a carousel component.

### Anatomy

Carousel navigation is composed of:
1. an arrow
2. a rounded container

### States

Carousel navigation has four possible states:
* Default
* Hover
* Pressed
* Disabled

### Appearance

Carousel navigation includes a black chevron which is set within a 50% white container to allow them to remain visible when placed over different colored backgrounds or imagery.
The 20% transparency is applied to the Default & Disabled States.
The carousel navigation is not displayed anymore under the Medium Screen size break point.

### Placement

The carousel navigation is positioned to the left and right edges of the carousel and centered vertically. For more examples of the carousel navigation used in hero banners, see the promotions examples in modules.

### Interaction

* Mouse: the component must be clickable
* Keyboard: the component will inherit the button interaction (focus + press "Enter")
    * Note: the carousel can also be manipulated with "left" and "right" keys but it will handle itself this behavior
* Touch (mobile): the component will inherit the button behavior on mobile
    * Note: the carousel can be manipulated by swiping the content but it will handle itself this behavior

### Animations

No animation for this component

## Accessibility

A good practice on [carousel accessibility](https://www.w3.org/WAI/tutorials/carousels/working-example/)

### Visual Accessibility

The image won't be used by screen readers; a visually hidden text will be used to inform the purpose of the commands: "Previous" / "Next".

#### Question: How the visible focus will be displayed?

- [ ] Check the current implementation to see if it is possible to have a visible focus (an outline) just around the button

### Usage Accessibility

N/A

## Technical specifications

This component won't be considered as a component but rather as a part of the Carousel component. So it won't be provided on its own.

### HTML Structure

The base HTML element will be a `<button>`.
The icon will be displayed within `<span>` (that must be hidden for screen reader) with a `:before` rule.
The image must be embedded by Boosted.

### JavaScript

No JavaScript directly for this component. JS will be handled by the Carousel component.

### Documentation in Boosted

Since this component can only be used within a carousel, it won't exist on its own and will be packaged in the Carousel component.

No need to create a specific Example page.

## Implementation tasks

- [x] #1137

**Comment by Franco-Riccitelli** [comment]
Correction to the **Appearance** specified for the white container in the description above.
The carousel navigation is set within a **50%** white container _not_ 20%.

**Comment by MewenLeHo** [comment]
Desired focus state for carousel prev and next button will not be easy to achieve because : 
- they are positionned thanks to absolute positionning so they have no height
-  we are supposed to add an orange circle for the focus PLUS a white background between the element and the focus line in order to prevent accessibility issues caused by the sliding image.

=> i made a CodePen with a preliminary test and I would like to have feedbacks on it:

[https://codepen.io/MewenLeHo/pen/MWrXNZg?editors=1100](https://codepen.io/MewenLeHo/pen/MWrXNZg?editors=1100)

@julien-deramond @louismaximepiton @Franco-Riccitelli

**Comment by louismaximepiton** [comment]
I might be wrong, but I think you tried too much to put the focus state on the button and not its descendant. I tried some few things on this [Codepen](https://codepen.io/louismaximepiton/pen/xxpaxYy?editors=1100) and I think it is much easier this way !

**Comment by MewenLeHo** [comment]
I just updated the demo CodePen: https://codepen.io/MewenLeHo/pen/MWrXNZg?editors=1100

**Comment by MewenLeHo** [comment]
FYI approved by the Design team.

**Comment by MewenLeHo** [comment]
And approved by the a11y Team as well.
