### ISSUE TITLE
Checkbox checked not well displayed

### ISSUE THREAD

**Issue by sebprev** [Orange-OpenSource/Orange-Boosted-Bootstrap#11]
Hello,
It seems that the Checkbox set to checked has a display bug.
The background of checkbox has the Orange Brand Color but the color exceed the bottom border like shown in the following pic and for the **idChk3** in showcase page:

![capture](https://cloud.githubusercontent.com/assets/12940873/19194134/04a66e10-8cad-11e6-991f-9891ab73f91f.png)

KO with Chrome 48 & 53 and Samsung Browser 4.0 (Android)
Ok with IE 11 and Firefox 38

**Comment by Lausselloic** [comment]
Thanks for this feed back;

The commit f7cfb672ee7f19e88e7022309899ce9dce196a4f fixed it.

We will soon release a new version of boosted 3
