### ISSUE TITLE
[Boosted vs Brand stencils] Hint weight

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#110]
Stencil
![image](https://user-images.githubusercontent.com/13221271/51985191-9896dd00-249d-11e9-8b6c-e8aef6008084.png)

Boosted
![image](https://user-images.githubusercontent.com/13221271/51985199-9c2a6400-249d-11e9-8a1c-34bc2149c099.png)

**Comment by liyokuna** [comment]
[Check](https://boosted.netlify.com/docs/4.3/components/forms/#overview)
