### ISSUE TITLE
Bring back `form-control-sm`

### ISSUE THREAD

**Issue by MewenLeHo** [Orange-OpenSource/Orange-Boosted-Bootstrap#1100]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

According to Cyriaque : "In some exceptional cases we provide components with a lower dont 14 px font size such a Small button or Small quantity selector" : 

Therefore we need to put back small inputs (i.e. form controls with CSS class .form-control-sm) into Boosted.

### Motivation and context

It will be helpfull to simply use CSS class '.form-control-sm intead of doing weird things like what we have done for the quantity selector (i.e. '$input-padding-y-sm: divide($input-padding-y, 2) !default; // Boosted mod').

**Comment by louismaximepiton** [comment]
Since the `.form-control-sm` is back in Boosted, should we try to take a look at this one again ?

**Comment by julien-deramond** [comment]
Closing it since `.form-control-sm` is back to Boosted via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1230.
Create a new one to see if using `.form-control-sm` in our Boosted specific small form controls can be useful.
