### ISSUE TITLE
[Boosted vs Brand stencils] required input indicator

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#111]
Stencil
![image](https://user-images.githubusercontent.com/13221271/51985275-cda32f80-249d-11e9-87e9-be175b6c3eb8.png)

Boosted
No equivalent available

**Comment by Lausselloic** [comment]
documentation added https://boosted.netlify.com/docs/4.3/components/forms/#validation
TODO in V5 remove 
```
&.is-required label::after {
    margin-left: 6px;
    font-weight: $font-weight-bold;
    color: theme-color("primary");
    content: "*";
  }
``` 
from o-forms.scss keep for retro-compatibility but no more used neither documented

Also add is-required on all labels when needed
