### ISSUE TITLE
Progress bar display for small percentage completion

### ISSUE THREAD

**Issue by octavd** [Orange-OpenSource/Orange-Boosted-Bootstrap#1115]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hello,

For the progress bar i've noticed the following behavior:

- If we have a progress bar with a small percentage of completion - ex: 2%:
```
<div class="progress">
    <div class="progress-bar" role="progressbar" style="width: 2%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">2%</div>
  </div>
```

The progress bar will be displayed like below and doesn't seem that user friendly - the percentage sign is cut off:
![image](https://user-images.githubusercontent.com/33294589/155951254-1b98ab3b-6e7b-4c2c-8e5d-8134956bf4d3.png)

Checking the CSS for the .progress-bar i've noticed the following parameter:
`overflow: hidden;`

If we would remove this option from the .progress-bar css, we can see that the percentage is nicely displayed:
![image](https://user-images.githubusercontent.com/33294589/155951503-7b58e95d-7d73-477a-a99e-dd9fb3ad874c.png)

### Motivation and context

The progress bar text displayed in percentage will not be cut anymore if we have lower values for the progress bar.
See screenshots (before and after) above.

**Comment by julien-deramond** [comment]
Thank you for this issue. Indeed it would be better to remove the `overflow: hidden` or something like forcing `overflow: visible`. It seems that the fix could be easily done both in v4 and v5.

**Comment by julien-deramond** [comment]
I just dig into the history of Boosted / Bootstrap and found that this `overflow: hidden` is here for a reason: to hide by default the bar text when you have a 0% element:

```html
<div class="progress">
   <div class="progress-bar bg-warning" role="progressbar" style="width:0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">5%</div>
  <div class="progress-bar" role="progressbar" style="width: 25%;z-index:1" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
</div>
```

So for a single progress bar, you could use the `.overflow-visible` utility:
```html
<div class="progress">
  <div class="progress-bar overflow-visible" role="progressbar" style="width: 2%;" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100">2%</div>
</div>
```

For a multiple progress bar, you could play with the `z-index`; something like that (but the texts won't be well-rendered):
```html
<div class="progress">
   <div class="progress-bar bg-warning overflow-visible" role="progressbar" style="width: 2%;z-index:2" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100">5%</div>
  <div class="progress-bar" role="progressbar" style="width: 25%;z-index:1" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
</div>
```

**Comment by octavd** [comment]
It's ok with the `.overflow-visible` solution.
Thank you very much for your support!
