### ISSUE TITLE
Docs > Components > Pagination > Working with icons: Fix css

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1119]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Left and right arrows seem not to be centered in their squares. They seem to be 1 extra pixel towards right for the left arrow and 1 extra pixel towards left for the right arrow. 

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1.0

**Comment by hannahiss** [comment]
issue identified and corrected but I cannot push at the time

**Comment by hannahiss** [comment]
Fix only for pagination and back to top. Thanks Louis Maxime
