### ISSUE TITLE
[Boosted vs Brand stencils] text box error

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#112]
Stencil 
![image](https://user-images.githubusercontent.com/13221271/51985381-ff1bfb00-249d-11e9-859f-9a6d042ceea0.png)

Boosted
![image](https://user-images.githubusercontent.com/13221271/51985388-0216eb80-249e-11e9-8c94-3342daaeeed0.png)

**Comment by Lausselloic** [comment]
error messages fixed by commit : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/3460b60f0164541f74ac8b3be35232fcb9a89f6a 
Could be checked: https://boosted.orange.com/docs/4.2/boostwatch/#forms

**Comment by PigeardSylvain** [comment]
The error message seems smaller in Boosted ?

![image](https://user-images.githubusercontent.com/13221271/53177565-8ddced00-35f0-11e9-80d1-8a803dca9b3e.png)

**Comment by Lausselloic** [comment]
switched size to 14px could be tested https://boosted.netlify.com/docs/4.3/components/forms/#validation
@PigeardSylvain please close this issue if it's okay for you

**Comment by PigeardSylvain** [comment]
Thanks !
