### ISSUE TITLE
Docs > Components > Buttons > Dark background: Fix border color for social buttons on active state

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1121]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On https://boosted.netlify.app/docs/5.1/components/buttons/#dark-background, the value of border-color for social inverse buttons (= with a dark background) active state don't change, so on mouse down, visually, it seems that the buttons get smaller.

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Boosted are you using?

v5.1.0

**Comment by hannahiss** [comment]
I don't know how to reach the branch in which  dark background version of social buttons have been implemented.

**Comment by Lausselloic** [comment]
https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1010
https://deploy-preview-1010--boosted.netlify.app/docs/5.1/components/buttons/#dark-background
