### ISSUE TITLE
Dropdown component with search

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#1123]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hello

I was looking at the design system :
https://system.design.orange.com/0c1af118d/p/910b9b-dropdown/b/04c480

which has recommendations to use a drop-down with search but I can't find any code nor documentation on Boosted.
I've seen that they are several examples existing on the web (https://mdbootstrap.com/snippets/jquery/mdbootstrap/921549) but those seem to be no standard Bootstrap.

Do you have any recommendation to be able to get this component in Boosted documentation ?

Thanks in advance

### Motivation and context

This should be useful for Orange portals using funnel for delivery zones where the're could be multiple districts.

**Comment by julien-deramond** [comment]
Hello @MathieuPomm.

Indeed this component is not yet implemented in Boosted but we're working on it in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/943.

We are currently in a specifications phase:
* :warning: The design will probably change to remove the search input in the dropdown among other things
* We are studying the really good content of https://www.24a11y.com/2019/select-your-poison-part-2/ which allows to have an accessible component. As you can see @razyon proposed a prototype based on that in [a dedicated CodePen](https://codepen.io/razyon/full/rNYjQBm).

I you need this component ASAP you could:
* Start from this component (don't forget to verify the license)
* In Angular I know that you can have results close to what we want to achieve with [ng-select](https://github.com/ng-select/ng-select) for example

**Comment by MathieuPomm** [comment]
Hi @julien-deramond thanks for your feedback.
Basically, the search input would be a "key" feature for this component.... and the prototypes mentioned above seem to include the search input that could allow filtering of results (which could answer this need).
I'll consequently wait for the proposal of it (I understand that it might be delivered in v.5.2, right ?)

**Comment by julien-deramond** [comment]
> I understand that it might be delivered in v.5.2, right ?

We don't have a clear view of when Bootstrap will release the 5.2 (and so Boosted) but it seems to be rather soon. So this component would be rather in a version after the 5.2.

**Comment by MathieuPomm** [comment]
Noted Julien. Thanks.
Have anice day !
