### ISSUE TITLE
remove role=switch on switches

### ISSUE THREAD

**Issue by Aniort** [Orange-OpenSource/Orange-Boosted-Bootstrap#1152]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

on https://boosted.orange.com/docs/5.1/forms/checks-radios/#switches page, we need to remove the role=switch on these switches because role=switch needs to be used with an aria-check attribute
So to be more robust and to ensure more progressive enhancement, just remove the role=switch
references: https://adrianroselli.com/2019/03/under-engineered-toggles.html and https://adrianroselli.com/2021/10/switch-role-support.html

### Reduced test cases

https://adrianroselli.com/2021/10/switch-role-support.html

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

5.1.

**Comment by MewenLeHo** [comment]
According to @Aniort , the `aria-checked` attribute is not needed in a switch which is in a `input type="checkbox"` so we can keep Bootstrap's version.

**Comment by Aniort** [comment]
after futher more readings, we can close this PR because Bootstrap has made a good choice for the switches, so let's resume like that !
