### ISSUE TITLE
Create a boosted demo page

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/Orange-Boosted-Bootstrap#1170]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Create a demo page that will illustrate the creation of a web page with boosted including only a fiew componants as:
* a header: the name of the site is "Acme Product"
* a page title: "Demonstrate the creation of a fast builded page"
* a stepper: "Step 2 of 4"
* a form with a fiew fields
* a series of butons cancel / previous / next (Orange)
* a footer: link to the orange brand site and...

### Motivation and context

In order to support the Accessibility presentation that illustrates a demo creation page.

**Comment by B3nz01d** [comment]
@julien-deramond  How can I indicate to add this in the next sprint's triage?

**Comment by julien-deramond** [comment]
Before adding this into the next sprint's triage, we need more information about this feature / example:
- What's "Acme Product"?
- Do we have a design for this page validated by designers and a11y team?

**Comment by julien-deramond** [comment]
Will be tackled by https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1374
