### ISSUE TITLE
[Boosted vs Brand stencils] Toogle buttons with labels

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#118]
Border color different, focus not visible, no inactive state in Boosted.

Stencil
![image](https://user-images.githubusercontent.com/13221271/51988015-f3cbce00-24a3-11e9-91d7-8c1121051693.png)

Boosted
![image](https://user-images.githubusercontent.com/13221271/51988024-f75f5500-24a3-11e9-9dc5-46bb3e81f72d.png)

**Comment by liyokuna** [comment]
[done](https://boosted.orange.com/docs/4.2/boostwatch/#3-way-toggle)

**Comment by Lausselloic** [comment]
KO for me : https://boosted.netlify.com/docs/4.3/boostwatch/#3-way-toggle doesn't have the right look and feel
I think the component pointed by that issue is more `btn-group` https://boosted.netlify.com/docs/4.3/components/button-group/

**Comment by Lausselloic** [comment]
http://boosted.orange.com/docs/4.2/components/buttons/#checkbox-and-radio-buttons see if it's possible to custom that component easily to fit the stencil

**Comment by liyokuna** [comment]
PR #136

**Comment by liyokuna** [comment]
PR #136
