### ISSUE TITLE
[Boosted vs Brand stencils] standard table

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#119]
Checks are not well centered in Boosted

Stencil
![image](https://user-images.githubusercontent.com/13221271/51988209-6b99f880-24a4-11e9-8f43-92411dbc723e.png)

Boosted
![image](https://user-images.githubusercontent.com/13221271/51988217-6e94e900-24a4-11e9-951f-7bf317f64b65.png)

**Comment by liyokuna** [comment]
[done](https://boosted.orange.com/docs/4.2/boostwatch/#checkbox-table)
