### ISSUE TITLE
[Boosted vs Brand stencils] tabs light

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#120]
Stencil
![image](https://user-images.githubusercontent.com/13221271/51988288-9e43f100-24a4-11e9-96e9-15b369656dc8.png)

Boosted
No equivalent available

**Comment by liyokuna** [comment]
refs to f0680b65afb47d21e1f6accf46bc825cba8f7fcd.

**Comment by PigeardSylvain** [comment]
Do you have a link to test ?

**Comment by liyokuna** [comment]
[nav light](http://localhost:3333/~dev-server-init)

**Comment by liyokuna** [comment]
I will work on having a same size for item title.

**Comment by PigeardSylvain** [comment]
Your link is on your localhost : http://localhost:3333/~dev-server-init

**Comment by liyokuna** [comment]
I changed it to [new link](https://boosted.orange.com/docs/4.2/components/navs/#nav-light)

**Comment by PigeardSylvain** [comment]
It should be moved in the tab section : https://boosted.orange.com/docs/4.2/components/navs/#tabs
