### ISSUE TITLE
Nested tabs

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#121]
## References
* **Orange Design System**: [Components > Navigation](https://system.design.orange.com/0c1af118d/p/44331c-navigation/b/9105e6)

**Comment by Lausselloic** [comment]
If anybody could explain how that component could be used in a webpage, maybe there could be an implementation.
But at time for me it's looks like two components copy/paste on photoshop but without any functionnal idea behind.

**Comment by julien-deramond** [comment]
[Design specs available in Orange Design System](https://system.design.orange.com/0c1af118d/p/44331c-navigation/b/9105e6)
