### ISSUE TITLE
[Boosted vs Brand stencils] pagination

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#122]
Focus and hover effect should be same.

Stencil
![image](https://user-images.githubusercontent.com/13221271/51989335-21664680-24a7-11e9-801c-de36b9cd34bd.png)

Boosted
![image](https://user-images.githubusercontent.com/13221271/51989342-262afa80-24a7-11e9-9ea1-6fd3b9945b37.png)
![image](https://user-images.githubusercontent.com/13221271/51989346-27f4be00-24a7-11e9-8aaf-ab2c55c6896c.png)

**Comment by liyokuna** [comment]
done !

**Comment by Lausselloic** [comment]
I'm not aware with the changes made in commit https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/82e6eb5591f21686510e58759846507412f5f030 as specified, `selected` state is on black background and not on orange one. @PigeardSylvain and @liyokuna maybe I miss something?

Current display doesn't fit the stencil : 
![image](https://user-images.githubusercontent.com/11272238/54921522-41920f00-4f06-11e9-80e3-21fa83405c0f.png)

**Comment by Lausselloic** [comment]
@PigeardSylvain could you check now : https://boosted.netlify.com/docs/4.3/boostwatch/#pagination
I've revert some commit, the pressed effect is only on clic.
TODO: Define how to render the "hover" effect on "selected" element that's not define in stencil

**Comment by PigeardSylvain** [comment]
It's just fine, thank you !
