### ISSUE TITLE
[Boosted vs Brand stencils]

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#123]
No pressed effect in boosted.

Stencil
![image](https://user-images.githubusercontent.com/13221271/51989486-773aee80-24a7-11e9-9c84-25eccc55f44e.png)

Boosted

![image](https://user-images.githubusercontent.com/13221271/51989496-7b670c00-24a7-11e9-9273-63410d134410.png)
![image](https://user-images.githubusercontent.com/13221271/51989507-7efa9300-24a7-11e9-9bd7-cdde225ac8ea.png)

**Comment by liyokuna** [comment]
pressed... is close to cliked

**Comment by Lausselloic** [comment]
Looks like hover color had change? 
https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/bcaa42591819283b6e7a1bc452b5f931c93136bc move from black background as specified in stencil to orange background???
https://boosted.netlify.com/docs/4.3/boostwatch/#pagination

**Comment by Lausselloic** [comment]
@PigeardSylvain could you check now : https://boosted.netlify.com/docs/4.3/boostwatch/#pagination
I've revert some commit, the pressed effect is only on clic.

**Comment by PigeardSylvain** [comment]
It's just fine, thank you !
