### ISSUE TITLE
Apply visible focus design guidelines in all components

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1237]
This issue is a sub task of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1189 which contains the list of all components that need to be updated with the new visible focus design guidelines.

### Process
- Choose one use case in the list in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1189#issuecomment-1113126740
- Create a branch and a PR for this use case
- In the [list of uses cases](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1189#issuecomment-1113126740), add at the end of the corresponding line a link to the PR
- When the PR is merged, check the use case in the list

**Note:** Please try to avoid creating a PR that handles several use cases at the same time; it will be easier to track the use cases and easier for the reviewers with small PRs.

**Note:** This issue will be considered done (and can be closed) when all the use cases described in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1189#issuecomment-1113126740 are handled, checked and merged. Don't forget to close https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1189 as well.

**Comment by louismaximepiton** [comment]
Shall be closed ?
