### ISSUE TITLE
Prototyping Side Navigation component

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1238]
This issue is a study (sub task of #941) whose the goal is to provide a prototype to check the feasability of this component and give some feedback to specify this component in the DSM.

At the end of this prototyping phase, please gather information in the main issue in order to find the information more easily when we will develop the component.

**Comment by louismaximepiton** [comment]
Just a comment to tackle the advancement of this task.

### Codepen(s) associated
- https://codepen.io/louismaximepiton/pen/GRQMEqo

### Feasability
Seems to be feasible (at least the first one). No comments atm, waiting for mobile specs

### Miscellaneous
Dunno if feasible but : 
- [ ] Try to make one `body` for all variants
- [ ] Maybe only one class to change or to add such as : `.sidenav` `.sidenav-icon` `.sidenav-drawer` or `.sidenav-collapse`
- [ ] Study the feasability of the other variants
- [ ] Need to study a bit more tooltips
- [ ] maybe include heights for each item
- [ ] Need to study a bit more the behavior with navbars
