### ISSUE TITLE
[Boosted vs Brand stencils] stepped process

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#124]
Text is not centered in Boosted.

Stencil
![image](https://user-images.githubusercontent.com/13221271/51989576-a9e4e700-24a7-11e9-885f-22f772b287c6.png)

Boosted
![image](https://user-images.githubusercontent.com/13221271/51989593-acdfd780-24a7-11e9-8fcb-7a81d915d112.png)

**Comment by liyokuna** [comment]
[done](https://boosted.orange.com/docs/4.2/boostwatch/#stepbar)

**Comment by Lausselloic** [comment]
ok for me https://boosted.netlify.com/docs/4.3/components/stepbar/#mobile-stepbar
