### ISSUE TITLE
[Boosted vs Brand stencils] stepped process for mobile

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#125]
Thickness of separators is different, step numbers not present in Boosted.

Stencil
![image](https://user-images.githubusercontent.com/13221271/51989667-caad3c80-24a7-11e9-9cc5-7c0cb9d944eb.png)

Boosted
![image](https://user-images.githubusercontent.com/13221271/51989672-ce40c380-24a7-11e9-873c-e57f777fe5e2.png)

**Comment by Lausselloic** [comment]
Waiting for the arrow spec (height, width and weight)

**Comment by Lausselloic** [comment]
changing the current stepbar height won't be done in V4 let see if there's more informations on that component for V5
