### ISSUE TITLE
[Boosted vs Brand stencils] browsing alerts

### ISSUE THREAD

**Issue by PigeardSylvain** [Orange-OpenSource/Orange-Boosted-Bootstrap#126]
Alerts are different in Boosted.

Stencil
![image](https://user-images.githubusercontent.com/13221271/51989878-32fc1e00-24a8-11e9-873f-655290133441.png)

**Comment by Lausselloic** [comment]
version 4.2
browser IE11
Icons are missaligned for medium size
https://boosted.orange.com/docs/4.2/components/alerts/#outline

**Comment by Lausselloic** [comment]
okay for me could be see : https://boosted.netlify.com/docs/4.3/components/alerts/#outline
