### ISSUE TITLE
[RTL] — Tooltips / popovers in 4.3

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#129]
Playing with 4.3 Boostwatch in RTL mode, I found that tooltips right / left are indeed right / left, but their arrows aren't — thus displayed the wrong side of the dialog.

I’m not sure what's wrong here (should tooltip be the other side, or only the arrow?) but something's wrong :)

**Comment by Lausselloic** [comment]
tooltip position fixed by commit https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/45e244a86b1bb2bafceec9284385c8ea2ae5b880 
TODO: fix popover position who is out of the container

**Comment by Lausselloic** [comment]
popover fixed by commit : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/e141195d1dbb7ace81054502b3a097880a3c8941

Could be see in action : https://boosted.netlify.com/docs/4.3/boostwatch/rtl-index.html#dialogs

If it okay for you @ffoodd could you close this issue?

**Comment by ffoodd** [comment]
LGTM :)
