### ISSUE TITLE
Docs > Forms > Check-radios: Checkbox indeterminate state to add and correct

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1318]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue #1201 `List in all the doc the incompatibility with ODS` in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS". 
Doing this work, design bugs were noticed. 

### Design bug to be corrected:

**docs/5.1/forms/checks-radios/**
- **indeterminate**: 
    - [ ] background checkbox color on state indeterminate to be changed   
![image](https://user-images.githubusercontent.com/89514509/174823580-357869e4-e700-486a-9f02-a689ef1fb323.png)
    - [ ] background checkbox color on state indeterminate disabled to be changed
![image](https://user-images.githubusercontent.com/89514509/174824856-805d07fe-b562-4212-ab61-2d007ac6c622.png)

- **disabled**: 
    - [ ] add "Indeterminate checkbox" case
    - [ ] delete the checkbox active/pressed state on a disabled checkbox that make its border turn orange where there shouldn't be any color change.
![image](https://user-images.githubusercontent.com/89514509/174833233-d8647ba4-36c5-4ac8-b1b7-735136528989.png)

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.2

**Comment by julien-deramond** [comment]
Could you please create specific separate issues. Otherwise it will be complicated to track.
Note: bugs should not appear in sprints boards (I removed this issue from it)
