### ISSUE TITLE
Docs > Table > With icons or thumbnails: checkbox icon container size incorrect

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1319]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 List in all the doc the incompatibility with ODS in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS".
Doing this work, design bugs were noticed.

**Design bug to be corrected**:
- docs/5.1/content/tables/**with-icons-or-thumbnails**: the checkbox icon container shall be 40px x 40px instead of the present (30px x 30px + margin of 5px). See ODS specification "standard table with column header WEB-TBL-STD-003.

![image](https://user-images.githubusercontent.com/89514509/176119736-34907d51-bee5-463e-bf80-fd2a5a45b48e.png)

 => ODS specifications
https://system.design.orange.com/0c1af118d/p/21b04a-data-tables/b/56a1a9/i/66611045
![image](https://user-images.githubusercontent.com/89514509/176119937-af587904-d5a1-44f6-a7fe-4b6f638a79b1.png)

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1

**Comment by louismaximepiton** [comment]
I can't see the point here, is that a duplicate of #1236 ?

**Comment by louismaximepiton** [comment]
Seen with @isabellechanclou, the main issue here is that the `.table-sm` should have a height of 40px even with svg inside and the `.table` should have a height of 50px even with a svg inside.

**Comment by isabellechanclou** [comment]
I'm closing this issue because it will be treated in issue #1357 instead.
