### ISSUE TITLE
Docs > Forms > Input-group > Dropdown-with-button: Fix active button color + dropdown position 

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1323]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 List in all the doc the incompatibility with ODS in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS".
Doing this work, design bugs were noticed.

**Design bug to be corrected:**
- docs/5.1/forms/input-group/button-with-dropdowns: 
    - [ ] active state of dropdown button is incorrect. Colors need to be changed    
![image](https://user-images.githubusercontent.com/89514509/174972237-cc5e98c5-2b2a-4fc1-9b01-02b7bd5280ff.png)
    - [ ] dropdown list is 1 px too low 
![image](https://user-images.githubusercontent.com/89514509/174971671-0bda10f2-67cd-4b3a-a1bb-4778c046482d.png)

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1

**Comment by louismaximepiton** [comment]
Both may be tackled by #1164
