### ISSUE TITLE
Docs > Components > Badge: Fix pill-badge height + background color 

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1325]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 "List in all the doc the incompatibility with ODS" in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS".
Doing this work, design bugs were noticed.

**Design bug to be corrected:**
- docs/v5.1/components/badge/pill-badge:
    - [ ] The height is about the one indicated for the small variant in ODS, but not exactly. So correct the height to match the ODS one + say in the doc that the size is the small one
    - [ ] Fix background color for in ODS tags, there can't be any background color.

=> See Tags component design specifications on ODS:
https://system.design.orange.com/0c1af118d/p/975c09-tags/b/24dde8
https://system.design.orange.com/0c1af118d/p/975c09-tags/b/199d2d/i/66611049
![image](https://user-images.githubusercontent.com/89514509/176115887-c7c84e3b-2fc7-4d72-bdc0-20d2377887ea.png)

⚠️ As Tags and Badges are different components and that we think Boosted end users might want to use badges, it could be interesting to have them added in ODS to have a correct design, that might be different of the Badges one.
Before discussing that point with the design, let's add a alert message on the Badges page to say that it's not possible to add this components respecting ODS except the positioned variant (used in the orange global headers https://system.design.orange.com/0c1af118d/p/37609b-global-headers/b/366c91).
    
  **Note: This documentation paragraph will need review and other fixes later.**

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1

**Comment by louismaximepiton** [comment]
Could you please add a link to the specs because I can't figure out where they are.

**Comment by isabellechanclou** [comment]
Design specifications added in the issue description.
