### ISSUE TITLE
Update Tooltip and Popover design

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1329]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Modify the rendering of Boosted's tooltips and popovers based on the elements in the DSM:
- [Tooltip](https://system.design.orange.com/0c1af118d/p/932946-tooltip/b/417f3e)
- [Popover](https://system.design.orange.com/0c1af118d/p/644ffa-popovers/b/4946ab)

Optional in this issue: see if Guided tour popover can be created with basic popovers and/or cards. If not, create a separate specific issue.

### Pre-requisites

- [x] #1330

### Motivation and context

[Tooltip](https://system.design.orange.com/0c1af118d/p/932946-tooltip/b/417f3e) and [Popover](https://system.design.orange.com/0c1af118d/p/644ffa-popovers/b/4946ab) design is not the same than the one actually in Boosted.

**Comment by louismaximepiton** [comment]
Wasn't it closed by #1803 ?

**Comment by julien-deramond** [comment]
> Optional in this issue: see if Guided tour popover can be created with basic popovers and/or cards. If not, create a separate specific issue.

Closing this one and creating a separate issue.
