### ISSUE TITLE
Prototyping white arrow with outline for tooltips and popovers

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1330]
Check if the rendering proposed for the following components is possible:
- [Tooltip](https://system.design.orange.com/0c1af118d/p/932946-tooltip/b/417f3e)
- [Popover](https://system.design.orange.com/0c1af118d/p/644ffa-popovers/b/4946ab)

We are talking here about the white arrow with a border.

**Comment by MewenLeHo** [comment]
First try: https://codepen.io/MewenLeHo/pen/jOzLLeL?editors=0100

It seems that the only way to to do this is to fake it with a second triangle shape. I will have a look for a better solution if possible.

**Comment by louismaximepiton** [comment]
Another idea would be to use `clip-path` which is [well supported](https://caniuse.com/css-clip-path) since we don't use external SVGs. Here is a [Codepen](https://codepen.io/louismaximepiton/pen/dymzJNw).
