### ISSUE TITLE
Docs > Components > Modal: fix margin between text and buttons

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1331]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 "List in all the doc the incompatibility with ODS" in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS".
Doing this work, design bugs were noticed.

**Design bug to be corrected:**

- In docs/v5.2/components/**modal/#live-demo**, the margin between the text "Woo-hoo, you're reading..." and the buttons below is too small.
![image](https://user-images.githubusercontent.com/89514509/175267860-29602bf1-efa3-48aa-a3cf-9b1f5abedf2d.png)

    **To do:**
    - [ ] Fix the margin. Refer to ODS spec at https://system.design.orange.com/0c1af118d/p/16d9f3-modals/b/774d3d/i/66611040

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1

**Comment by MewenLeHo** [comment]
As seen with @isabellechanclou: distance between text and buttons must be 40px on desktop and 35px on mobiles.
