### ISSUE TITLE
Better rendering for "Skip to main content" link

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1334]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Display the "Skip to main content" link in a specific nav in Boosted.

Thoughts @Aniort? Is is interesting/useful?

### Motivation and context

"Skip to main content" is displayed differently in Bootstrap and seems nicer.

![Screenshot from 2022-06-23 16-10-56](https://user-images.githubusercontent.com/17381666/175320075-f1da699c-0133-476f-a1b5-320c981d2994.png)

**Comment by louismaximepiton** [comment]
Could be grouped with #138

**Comment by julien-deramond** [comment]
Closing it in favor of #1694
