### ISSUE TITLE
Stepped-processs: underline not visible on hover

### ISSUE THREAD

**Issue by louismaximepiton** [Orange-OpenSource/Orange-Boosted-Bootstrap#1337]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The underline on hover isn't visible on some breakpoints maybe due to `line-height`. It might be for some browsers/OS.

What I have on main (I'm hovering review):
![image](https://user-images.githubusercontent.com/91960143/176638263-0b308a6f-7e13-4342-84e5-9e20c6f24115.png)

What I have on PR: 
![image](https://user-images.githubusercontent.com/91960143/176638503-deef8089-2d7c-42b1-b31b-58173f3a0136.png)

The letters are still cut, so maybe I should extend the line-height a bit more.

### Reduced test cases

https://main--boosted.netlify.app/docs/5.1/components/stepped-process/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Boosted are you using?

5.2.0 (current_main_branch)

**Comment by julien-deramond** [comment]
Could you please provide a screenshot of the issue. I don't reproduce it atm.
