### ISSUE TITLE
Custom checkboxes - Encoutered an issue to deselect it

### ISSUE THREAD

**Issue by Handja** [Orange-OpenSource/Orange-Boosted-Bootstrap#134]
Hi,

I've encountered an issue with custom checkboxes.
When I select it and after that i want to deselect it, I need to to click on the icon inside it.
If I click on the orange background nothing happens.

So some users think it's a bug.

https://boosted.orange.com/docs/4.2/components/forms/#checkboxes-and-radios-1

**Comment by Lausselloic** [comment]
Hello,
Oh you're right :-(
Just reproduce it on Chrome win7

We will try to fix it

**Comment by liyokuna** [comment]
#135

**Comment by Lausselloic** [comment]
@Handja fix will be available in the next release (4.3.1)

**Comment by Handja** [comment]
Ok thx you :)
