### ISSUE TITLE
Validation "OK" Check is missing for Select Tag

### ISSUE THREAD

**Issue by nicolasvarin** [Orange-OpenSource/Orange-Boosted-Bootstrap#1342]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,

Using Boosted 5.1 VS. Bootstrap 5.1, validation check icon is missing for boosted select HTML tag.

### Reduced test cases

To avoid integration issues, this bug is reproducible on Boosted/Boostrap demo sites.
https://boosted.orange.com/docs/5.1/forms/validation/
https://getbootstrap.com/docs/5.1/forms/validation

![bootstrap-valid-OK](https://user-images.githubusercontent.com/10230878/176137895-3ae4de9a-dc1d-4dd7-ae07-47867301a2e9.JPG)
![bootsted-valid-KO](https://user-images.githubusercontent.com/10230878/176137904-769762b2-643c-441c-a4a4-3e7285df7444.JPG)
/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

5.1

**Comment by julien-deramond** [comment]
Test notif

**Comment by julien-deramond** [comment]
Test notif @nicolasvarin

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @nicolasvarin.
Apparently it has been done on purpose few years ago

https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/aa8b4f061124ffd799f08160a1b822ddaf4cdb63/scss/mixins/_forms.scss#L91-L103

The validation icon is not displayed for textareas neither.

We need to check with the designers those cases.

**Comment by nicolasvarin** [comment]
Thank you Julien.
This looks like an arguable choice to me as there is no clear way to tell that a selectbox is valid (apart from the lack of red border).
Also, the user experience is different for selectboxes and textareas only, which sound arbitrary.
In the end, a valid form looks a bit off, uneven.

**Comment by julien-deramond** [comment]
Agree with your arguments, it seems a bit off. I'll try to dig into the history of the project to find if a specific reason is mentioned somewhere and we'll discuss with the designers to have their point of view. Mixing all of that and provide a PR to have something more consistent :)
