### ISSUE TITLE
Docs > Forms > Input group > Segmented buttons: Move input field 1px right

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1365]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 List in all the doc the incompatibility with ODS in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS".
Doing this work, design bugs were noticed.

**Design bug to be corrected:**

- /docs/5.1/forms/input-group/#segmented-buttons: 
    - [x] 1st variant: Move input field 1 px to the right to let the left vertical border show (in light grey). To do that, add the `ms-0` class to the `<input>` ones.
    Now:
    ![image](https://user-images.githubusercontent.com/89514509/177553429-008e409b-8413-4754-9cab-cee9bc3132ca.png)
    How it should be:
    ![image](https://user-images.githubusercontent.com/89514509/177554087-2bd50bcf-e4e8-4f4b-8d6a-168fd9055f17.png)
    ![image](https://user-images.githubusercontent.com/89514509/177555594-a1bea45a-6bac-4f36-b077-e3b3a4efd609.png)

    - [x] 2nd variant: Move input field 1 px to the left to let the right vertical border show (in light grey). To do that, add the <del>`me-0`</del>  `ms-0` class to the `<input>` ones.
    Now:
    ![image](https://user-images.githubusercontent.com/89514509/177555736-8e373e6c-b5f4-4670-b25d-9a5a8419a02c.png)
    How it should be:
    ![image](https://user-images.githubusercontent.com/89514509/177555305-d5c53708-fed9-4747-95aa-13a347f8d9b0.png)
    ![image](https://user-images.githubusercontent.com/89514509/177555448-7795d2b3-8f08-42dc-b1ee-727da52bfcb2.png)

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1

**Comment by isabellechanclou** [comment]
Indeed, I made a mistake, i really meant `ms-0`, as you did.

**Comment by julien-deramond** [comment]
Based on the discussion with designers, it was decided to keep the actual behavior in Boosted. Closing this one.
