### ISSUE TITLE
Docs > Components > Buttons > Icon only + No outline: Add missing tooltip

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1368]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 List in all the doc the incompatibility with ODS in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS".
Doing this work, design bugs were noticed.

**Design bug to be corrected:**

- docs/v5.1/components/buttons:
    - [ ] **#icon-only**, **#no-outline**: In ODS, both of these components should have a tooltip on hover => to add.
       ⁉️ Question asked to designers:  what is the default place for tooltip (above the button or below it as illustrated on ODS website) ?  
**Answer**: Place the tooltip below the button as illustrated in ODS:
![image](https://user-images.githubusercontent.com/89514509/206758754-b3efbdd1-0b49-4256-933f-dfee4dd152bf.png)

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1

**Comment by julien-deramond** [comment]
Closing it since tackled by https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1823
