### ISSUE TITLE
Docs > Components > Card > Using grid markup: fix margins between cards in small screens

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1369]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 "List in all the doc the incompatibility with Orange Design System (ODS)" in which all Boosted components (variants included) have been inspected. The goal was to identify the components that do not respect the Orange Design System specifications and therefore need the addition of an alert message informing that they can't be used in Orange web applications.
Doing this work, design bugs were noticed.

**Design bugs to be corrected in the issue:**

- In docs/v5.2/components/**cards/#using-grid-markup**: when the screen is smaller than 480px, cards are displayed vertically but without any margin.        
    ![image](https://user-images.githubusercontent.com/89514509/177592831-52bd6503-413e-4a83-9f08-2cab6bc834e8.png)
    **Fixes to do**:  
    - [ ] add a vertical margin for this screen size. Try with a margin of 10px to see if it is enough (don't go over 20px)
    - [ ] ask Bootstrap for doing this same fix

- In docs/v5.2/components/**cards/#using-utilities**: when the screen is smaller than 768px, cards are displayed vertically but without any margin. 
     ![image](https://user-images.githubusercontent.com/89514509/177594595-fa29c055-85fe-4caa-9422-6aeff86d9911.png)
    **Fix to do**:
    - [ ] add a vertical margin for this screen size. Try with a margin of 10px to see if it is enough (don't go over 20px)
    - [ ] ask Bootstrap for doing this same fix

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1

**Comment by julien-deramond** [comment]
Closing it. Tried to tackle it directly in Bootstrap via https://github.com/twbs/bootstrap/pull/37493. Will reopen this issue if Bootstrap PR is refused.
