### ISSUE TITLE
Docs > Components > Dropdowns > Single button + Menu items: Complete doc about dropdown html semantic

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1372]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 List in all the doc the incompatibility with ODS in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS".
Doing this work, design bugs were noticed.

Design bug to be corrected:

- docs/v5.1/components/dropdowns:
   - [x] **#single-buttons**: review with Vincent for accessibility the html semantic of 
       - [x] the dropdown field: from an accessibility point of view, is it OK to use indifferently a `<a>` html tag or a `<button>` html tag, or is it possible to use only a `<button>` tag? 
       - [x] the dropdown menu: why `<ul><li><a>item</a></li><ul>` is used and not `<ul><li><button> item</button></li></ul>`. If it is possible to use `<ul><li><button> item</button></li></ul>`, it could be useful to say that in the doc + say if there is a case where it is better to use one instead of the other (e.g.: `<a> for a change of page`)
   
   - [x]  #menu-items: 
       - [x] the dropdown field: from an accessibility point of view, is it OK to use indifferently a `<a>` html tag or a `<button>` html tag, or is it possible to use only a `<button>` tag? 
       - [x] the dropdown menu: the `<ul><li><button>item</button></li><ul>` is used and not `<ul><li><a> item</a></li></ul>`. If it is possible to use `<ul><li><a> item</a></li></ul>`, it could be useful to say that in the doc + say if there is a case where it is better to use one instead of the other (e.g.: `<a> for a change of page`)

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.1

**Comment by julien-deramond** [comment]
The associated PR has been closed (see https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1412#issuecomment-1317019234). @isabellechanclou Can we close this issue as well?
