### ISSUE TITLE
Skip links new generation

### ISSUE THREAD

**Issue by Aniort** [Orange-OpenSource/Orange-Boosted-Bootstrap#138]
hello,
in our accessibility Team EASE, we think we have found a solution to improve skip links. Most of the time, skip links are hidden if you don't use the keyboard but it's unusable when you use a mouse.
So we need to have skip links: 
- at least visible when you are on the top of the page and hidden when you scroll (functionally like: https://deploy-preview-130--boosted.netlify.com/docs/4.3/components/navbar-orange/#supra-bar)
- but, when the skip links bar is hidden (the user have scrolled down) it must always have visually (a tab, a button...?) something present on the top of the page to reveal (on hover or on click) the skip links bar
Could we together study that component?
thanks

**Comment by Aniort** [comment]
some more functionalities to add compare to supra-bar:
- these skip links are useful for mobile user so the suprabar should remain visible on small screens
- even if the suprabar disappear when scrolling down, perhaps on click, the suprabar must disappear too
what do you think?

**Comment by julien-deramond** [comment]
Closing it in favor of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1694
