### ISSUE TITLE
Focus visibility

### ISSUE THREAD

**Issue by Aniort** [Orange-OpenSource/Orange-Boosted-Bootstrap#139]
hello,
to be fully compliant with wcag 2.1, we have to study the focus visibility on each interactive component, it must be improved in size and in term of contrast !
could we take time to study this all together, 
thanks

**Comment by Lausselloic** [comment]
related to #101

**Comment by ffoodd** [comment]
Start to work on this in v5-alpha:

- [ ] `focus-visible` polyfill and styles
  - [ ] apply `outline`s in `@if $enable-shadows { } @else { … }`

**Comment by ffoodd** [comment]
Every `:focus` indicator (when navigating with keyboard) is now:
* a `2px` `solid` `outline`,
* with an `offset` depending on the target size,
* and doubled where possible with a `box-shadow` to ensure visibility.

It may require deeper investigations, but from now on the `:focus` basis is very sane—with the noticeable exception of our main `orange`, as usual…
