### ISSUE TITLE
input-sm font size is too big

### ISSUE THREAD

**Issue by YannBertrand** [Orange-OpenSource/Orange-Boosted-Bootstrap#14]
On inputs and selects, the font exceed the field height: (screenshots from the docs)

![input_input-sm](https://cloud.githubusercontent.com/assets/5855339/19468522/11cd1e00-9517-11e6-8f32-7044bae87e94.png)
![select_input-sm](https://cloud.githubusercontent.com/assets/5855339/19468521/11ace568-9517-11e6-9dcc-23cebf11f8cd.png)

**Comment by Lausselloic** [comment]
Yes, we've seen it. Fixed by commit 9be9dfe571408075c05850a566c8b2745af0c56d

**Comment by YannBertrand** [comment]
Will you correct this in v3?

**Comment by Lausselloic** [comment]
Sorry, just saw it in v3 : http://boosted.orange.com/css/#forms-control-sizes

We will try to fix it

**Comment by YannBertrand** [comment]
Thanks :smile:

**Comment by ygatesoupe** [comment]
Hi, this is fixed in commit 31e7dc6b48ba694b
