### ISSUE TITLE
o-tab - move tab to accordions create responsive classes

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#140]
Related to issue #131 
For V5 maybe think like navbar-sm to create a class by screen size to allow project to use the dedicated size

Study the opportunity to create classes like o-tab-{xs|sm|md|lg|xl}

**Comment by ffoodd** [comment]
Related: #456

**Comment by ffoodd** [comment]
Closing this in favor of #150
