### ISSUE TITLE
Dropstart toggle split rendering compared to other dropdown toggle splits

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1492]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The split line rendering is different for [Dropstart toggle split](https://boosted.orange.com/docs/5.2/components/dropdowns/#dropstart) than for [Dropend toggle split](https://boosted.orange.com/docs/5.2/components/dropdowns/#dropend) or [Dropup toggle split](https://boosted.orange.com/docs/5.2/components/dropdowns/#dropup); the line is not cut at the edges:
<img width="190" alt="Capture d’écran 2022-08-29 à 10 38 09" src="https://user-images.githubusercontent.com/17381666/187160315-9dec4311-d09c-4c67-b79e-05a3d191504b.png">

### Reduced test cases

Simply go to https://boosted.orange.com/docs/5.2/components/dropdowns/#dropstart

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

v5.2.0

**Comment by louismaximepiton** [comment]
Should be fixed by #1164.
