### ISSUE TITLE
Tabs to accordion for small screen

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#150]
Relates to #456 #131 #140 

## Keyboard access

On responsive tab component switching from tab to accordions the keyboard pattern is not implemented and it's impossible to switch from one tab to another with arrows.

Maybe linked to accordion pattern. So need to check how to improve that

## Responsiveness

For V5 maybe think like navbar-sm to create a class by screen size to allow project to use the dedicated size

Study the opportunity to create classes like `o-tab-{xs|sm|md|lg|xl}`

**Comment by ffoodd** [comment]
Also relates to #140

**Comment by ffoodd** [comment]
FWIW I'd recommend to keep the tabpanel pattern for keyboard behaviour on small screen, and simply make tabs a single column. It'd be much simpler.

See [Inclusive Design Pattern's "Tabbed Interface"](https://inclusive-components.design/tabbed-interfaces/) which includes a note about "Accordions for small viewports?".

**Comment by ffoodd** [comment]
Related: #456

**Comment by ffoodd** [comment]
Dropped by our Global Design Language team.
