### ISSUE TITLE
Doc > Accordion > Dark variant : fix border bottom position on the last accordion item

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1537]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On the last item of an accordion (dark variant), the border bottom is 1px to low, making think that it is the focus that is not correct.
![image](https://user-images.githubusercontent.com/89514509/192501834-9b977e83-1fc1-42a1-843f-fbbae85f293a.png)

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.2

**Comment by MewenLeHo** [comment]
I have a look today and I was unable to reproduce the issue. I asked @isabellechanclou and she was unable to reproduce it as well.

Isabelle will have a look tomorrow, it may be specifically related to her panoramic screen.

**Comment by isabellechanclou** [comment]
After verification on Windows and Mac Os + Firefox and Chrome, this bug can't be reproduced anymore. As everything looks ok, I'm closing this issue.

**Comment by isabellechanclou** [comment]
After verification on Windows and Mac Os + Firefox and Chrome, this bug can't be reproduced anymore. As everything looks ok, I'm closing this issue.

**Comment by isabellechanclou** [comment]
After verification on Windows and Mac Os + Firefox and Chrome, this bug can't be reproduced anymore. As everything looks ok, I'm closing this issue.
