### ISSUE TITLE
Adding opacity in tooltips

### ISSUE THREAD

**Issue by LudovicSoltysOAB** [Orange-OpenSource/Orange-Boosted-Bootstrap#156]
Hello,

The default opacity of tooltips seems to be 80%. It would be nice to be able to change it.
If Orange Boosted already allows devs to configure it, could you add some details in the docs about how to do it ?
If this feature does not exist, can you add it ?

best regards,
Ludovic

**Comment by Lausselloic** [comment]
Hello,

Yes you could do it by recompiling scss file of boosted and by changing the value in `variables.scss` file https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v4-dev/scss/_variables.scss#L950

Or by setting 
```
.tooltip.show {
opacity: 1;
}
```

In your project css files

**Comment by ffoodd** [comment]
Since transparency is harder for reading, I just changed tooltip's opacity to fully opaque when shown.
