### ISSUE TITLE
Switch issue on iOS

### ISSUE THREAD

**Issue by louismaximepiton** [Orange-OpenSource/Orange-Boosted-Bootstrap#1576]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The square inside the switch isn't well displayed:

![image](https://user-images.githubusercontent.com/91960143/198290832-d5b4b24c-e663-4cc5-83fa-571b08d25e4c.png)

This is surely due to a `linear-gradient` that is not well supported on iOS ?

### Reduced test cases

Go on https://main--boosted.netlify.app/docs/5.2/forms/checks-radios/#switches with an iOS device.

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What version of Boosted are you using?

5.2.2 (current_main_branch)

**Comment by razvn** [comment]
also on macOS (Ventura)
