### ISSUE TITLE
TarteAuCitron language set to french?

### ISSUE THREAD

**Issue by MewenLeHo** [Orange-OpenSource/Orange-Boosted-Bootstrap#1584]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Boosted documentation is written in english,  the `lang` attribute on the `html` tag is set to 'en' but the cookies banner by TarteAuCitron is displayed in french:

![screenshot-localhost_9001-2022 11 02-09_46_21](https://user-images.githubusercontent.com/92363071/199442784-6131409f-f20f-4440-8c9b-c5c2bde614b1.png)

Would it be a good idea to set it in english for a better consistency?

### Reduced test cases

Possible solution: use the `tarteaucitronForceLanguage` variable **before** initializing Tarteaucitron in site\assets\js\tac.js.

```
var currentLanguage = document.documentElement.lang
window.tarteaucitronForceLanguage = currentLanguage
```

Therefore we can have:

![screenshot-localhost_9001-2022 11 02-09_47_28](https://user-images.githubusercontent.com/92363071/199446290-80722da9-f439-4242-a08c-6da7e6f904c0.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

5.2.0

**Comment by julien-deramond** [comment]
My OS and my browsers are set in English. When I go to boosted.orange.com with Chrome, the message is well displayed in English:

<img width="1442" alt="Screenshot 2022-11-02 at 10 07 10" src="https://user-images.githubusercontent.com/17381666/199449175-ee69205d-a509-4abb-9e10-05d1e722e92c.png">

**Comment by MewenLeHo** [comment]
It seems that the TarteAuCitron defines the language based on browser language indeed. I have never realized that before being force to reinstall Chrome 😮 

So it may be useless to change it. Except if we want to force it in english for everyone.


> My OS and my browsers are set in English. When I go to boosted.orange.com with Chrome, the message is well displayed in English:
> 
> <img alt="Screenshot 2022-11-02 at 10 07 10" width="1442" src="https://user-images.githubusercontent.com/17381666/199449175-ee69205d-a509-4abb-9e10-05d1e722e92c.png">

**Comment by julien-deramond** [comment]
IMO we don't want to force the language in English for everyone. All users must be able to understand how we handle the cookies.
