### ISSUE TITLE
Docs > Components > Tooltip > Directions: Fix responsive behavior

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1595]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**Design bug to be corrected:**
In docs/v5.1/components/tooltip/**#directions**, fix responsive behavior to have a correct display on the different breakpoints to avoid the case illustrated below. See if it is possible to do so by adding some css.
    ![image](https://user-images.githubusercontent.com/89514509/178006390-64f239db-e380-48ed-9b35-5bef46d93882.png)

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.2

**Comment by julien-deramond** [comment]
I'm closing this one because handled directly in Bootstrap via https://github.com/twbs/bootstrap/pull/37492. If the latter is refused, I'll reopen this issue here.
