### ISSUE TITLE
Docs > Components > Modal: fix inner modal scroll when long content

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#1601]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This issue comes from the work done in Issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1201 "List in all the doc the incompatibility with ODS" in which all Boosted components (variants included) have been inspected in order to identify the ones that do not respect ODS specifications and therefore need an alert message saying "Do not use in ODS".
Doing this work, design bugs were noticed.

**Design bug to be corrected**:
- In docs/v5.1/components/**modal/#scrolling- long-content**: their should be a scroll inside the modal because the content is very long, but it's not there. 

    ![image](https://user-images.githubusercontent.com/89514509/200547889-9dbbc959-907c-490f-b09d-fe1997e2d356.png)
    
    **To do**: 
    - [ ] Make the scroll appear an work in demo example 1

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.2

**Comment by julien-deramond** [comment]
@isabellechanclou There are two examples in https://boosted.orange.com/docs/5.2/components/modal/#scrolling-long-content. The first is the behavior by default without a scrollbar and the second with the scrollbar. I think I don't understand the description of this issue; what's described in the documentation seems OK 🤔 Am I missing something?

**Comment by isabellechanclou** [comment]
Ok, it seems I misunderstood the purpose of this 1st demo. So, indeed, this PR can be closed because there is nothing to fix.
