### ISSUE TITLE
Dark dropdown in navbar is not correctly vertically aligned

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1607]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Dark dropdown in navbar example in https://boosted.orange.com/docs/5.2/components/dropdowns/#dark-dropdowns is not correctly vertically aligned.

![Screenshot 2022-11-15 at 07 43 19](https://user-images.githubusercontent.com/17381666/201847324-af4a1497-a176-4e9e-9f03-98f1ac0e09a1.png)

I'm not sure but the height seems to be off as well compared to our global headers 🤷 

### Reduced test cases

See https://boosted.orange.com/docs/5.2/components/dropdowns/#dark-dropdowns.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

v5.2.1

**Comment by MewenLeHo** [comment]
I had a look on your issue and I was unable to reproduce it.
Could you please add more informations and screenshots?

**Comment by MewenLeHo** [comment]
Vertical alignment is exactly the same as the others `.nav-items`:
![screenshot-boosted orange com-2022 11 15-09_08_24](https://user-images.githubusercontent.com/92363071/201864416-a8b1b614-0055-4491-a2b3-644558b7f843.png)

**Comment by julien-deramond** [comment]
Something is off and maybe not fixable but the correct alignment is done on the text baseline normally

![Screenshot 2022-11-15 at 09 34 03](https://user-images.githubusercontent.com/17381666/201869870-556c3bd7-a0aa-4f4c-93ce-d46937b1a3a9.png)
