### ISSUE TITLE
Custom carousel

### ISSUE THREAD

**Issue by StreiffBerenice** [Orange-OpenSource/Orange-Boosted-Bootstrap#161]
@liyokuna I'm asking a question : is it logical to have firstly the focus on the circles "diapo 1", "diapo 2" etc before having the focus on the arrows " previous" and "next". See the custom [carousel ](https://boosted.orange.com/docs/4.3/boostwatch/#custom-carousel).

**Comment by ffoodd** [comment]
Hi there,

we won't fix this on for now, but we'll ensure to take this into account for the next major release (v5).
Thanks!
