### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by StreiffBerenice** [Orange-OpenSource/Orange-Boosted-Bootstrap#165]
@liyokuna Local navigation bar : the current link isn't very clearly indicated because it's only marked with colour. So, some people don't see very well the colour. Solution : keep the different colour for the current link and add a line under the link. For the white local navigation, don't use the orange colour. See orange Brand and choose the red/orange which have a suficient colour contrast. See the component [local navigation bar](https://boosted.orange.com/docs/4.3/boostwatch/#local ).

**Comment by ffoodd** [comment]
Color is defined by the Digital Brand Guidelines.

However current states has been improved in #273 (since Brand Guidelines is not taking care of this).
