### ISSUE TITLE
Modal Window

### ISSUE THREAD

**Issue by StreiffBerenice** [Orange-OpenSource/Orange-Boosted-Bootstrap#166]
@liyokuna Focus isn't visible. Use a 2 px and continuous with an adapted colour contrast for each button. See the [Modal Window](https://boosted.orange.com/docs/4.3/boostwatch/#modal) component.

**Comment by ffoodd** [comment]
Fixed by [commit #43dd339](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/213/commits/43dd33974d711268cd22dc30762cf08493d5fcbb).
