### ISSUE TITLE
Navs

### ISSUE THREAD

**Issue by StreiffBerenice** [Orange-OpenSource/Orange-Boosted-Bootstrap#167]
@liyokuna Breadcrumbs : current link should be indicated for example by a colour with a correct contrast between the text and its background, and a visual indicateur like an horizontal line under the link. See the [Breadcrumbs ](https://boosted.orange.com/docs/4.3/boostwatch/#nav) component.

**Comment by ffoodd** [comment]
FWIW, Boostwatch's example for breadcrumbs was obsoloete. I updated it in [a dedicated commit](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/213/commits/f8a637664c9e0adedb01ba48231f0d05453f4ebf).

There's still some work aligning with Orange brand's Navigation stencils.
