### ISSUE TITLE
Priority bar

### ISSUE THREAD

**Issue by StreiffBerenice** [Orange-OpenSource/Orange-Boosted-Bootstrap#169]
@liyokuna 
The focus must be more visible - > 2 px and continuous line. You shoul not use orange but the red/orange or dark grey to make the focus more visible.
See the [component ](https://boosted.orange.com/docs/4.3/boostwatch/#progress).

**Comment by ffoodd** [comment]
Fixed by [commit #43dd339](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/213/commits/43dd33974d711268cd22dc30762cf08493d5fcbb).
