### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by StreiffBerenice** [Orange-OpenSource/Orange-Boosted-Bootstrap#171]
@liyokuna the grey horizontal line are not lisible and the checkboxes are white on orange instead of black on orange. See the [table ](https://boosted.orange.com/docs/4.3/boostwatch/#tables) component.

**Comment by ffoodd** [comment]
This is unfortunately not allowed by Orange digital guidelines for now, however we plan to add a contrast enforcemtn widget with #209 — which would help dealing with invalid contrast.

Be sure we won't forget this one :)
