### ISSUE TITLE
Carousel with captions not working correctly

### ISSUE THREAD

**Issue by MewenLeHo** [Orange-OpenSource/Orange-Boosted-Bootstrap#1765]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

[Carousel with captions](https://boosted.orange.com/docs/5.2/components/carousel/#with-captions)

1. The carousel has a `data-bs-ride="false"` which is useless because `false` is the default value of this atribute according to our documentation.
2. The carousel doesn't have a `data-bs-pause` attribute, meaning that the default value `false` should apply and that the carousel must be set to `pause` on hover. However the carousel doesn't pause on hover.
3. The indicator of the first slide is running endlessly.
4. When you change the active slide, the indicators stop running.

### Reduced test cases

[Carousel with captions](https://boosted.orange.com/docs/5.2/components/carousel/#with-captions)

[screencast-localhost_9001-2023.01.09-10_21_59.webm](https://user-images.githubusercontent.com/92363071/211275878-e40b8483-6f14-4cd8-be34-34d07136450d.webm)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.2.3

**Comment by louismaximepiton** [comment]
Might be tackled by https://github.com/twbs/bootstrap/commit/0444d2cfe53390d6eaf86e8a6f6976309bb0ad25 since they initialize all the carousels in the doc.
