### ISSUE TITLE
Change rendering of help texts

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#1767]
Help text has been added in the UI Kit v5 in the Forms artboard. It corresponds to our `.form-text` when used under a form control (generally an input or a text area). You can see an example at https://boosted.orange.com/docs/forms/overview/#overview where "We'll never share your [...]" is an Help text.

This issue is meant to be an update of the rendering of those help texts in all the documentation and the code.

Help text is no more a basic text but has the following characteristics (please double-check with the UI Kit v5):
* color: `#666`
* font size: `14px`
* line height: `16px`
* letter spacing: `-0.1px`
* font weight: `bold`
* margin between the component and the input: `6px`

**Comment by hannahiss** [comment]
Created PR #1948 to fix the margin problem
