### ISSUE TITLE
Add social networks icons: instagram, linkedin, youtube, whatsapp

### ISSUE THREAD

**Issue by nicocoudert** [Orange-OpenSource/Orange-Boosted-Bootstrap#179]
Can you add new class: intsagram, linkedin, youtube, whatsapp for social buttons.
Rgd nicolas

**Comment by liyokuna** [comment]
Your request is right [here ](https://boosted.orange.com/docs/4.3/components/buttons/#social-buttons) @nicocoudert.
Does it fit your needs ?

BR

**Comment by nicocoudert** [comment]
Hi Lionel, No, As written in the subeject of my post I need instagram, youtube and whatsapp icons, pinterest too. Is it possible to add them as thos already online [here](https://boosted.orange.com/docs/4.3/components/buttons/#social-buttons)?

**Comment by liyokuna** [comment]
oh ok. I copied-paste after reading LinkedIn in the first place.
It can be added.

**Comment by nicocoudert** [comment]
No problem, let met me know when new classes will have been added.

**Comment by Lausselloic** [comment]
Also need to remove Google+ icon.
Need input from @philparry or other brand team for icon color and effect active, hover and focus states

**Comment by nicocoudert** [comment]
Hi, any update on this issue?

**Comment by nicocoudert** [comment]
Hi team, I come back to you about this issue, can you make me a status on this request? Thx Nicolas

**Comment by nicocoudert** [comment]
Thx Loic

**Comment by ffoodd** [comment]
Also added Pinterest and Snapchat as required by new buttons stencils.
