### ISSUE TITLE
pull back link with arrow from V3

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#19]
Following the feature onto v3, adding a class for link with arrow
https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/7dcc589309a1d66be976ed02f4c6de8fc55793b6

Need to implement it onto V4

**Comment by ygatesoupe** [comment]
Implemented in commit 357a228
