### ISSUE TITLE
Improve popover's arrow appearance

### ISSUE THREAD

**Issue by MewenLeHo** [Orange-OpenSource/Orange-Boosted-Bootstrap#1922]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Coming from #1803 

The width of the border's arrow seems thiner and is missing 1 (or 2?) px.

It seems not related to the way CSS handle diagonal lines.

![227134473-d00b5519-c02f-454b-9204-f88cce6715f5](https://user-images.githubusercontent.com/92363071/227896322-7746be93-6a53-4ebf-8185-73ca1146da8a.png)

### Reduced test cases

A solution can be to play with `::before` (probably not the` left/right` values), and the `border` widths because the "white area" is too large and hides 1px from the 2px border of the arrow.

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Boosted are you using?

v5.3.0

**Comment by louismaximepiton** [comment]
Already talked about this [here](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1803#discussion_r1092967572),

Maybe a good solution would be `bottom: round(calc(var(--bs-popover/tooltip-border-width) * sqrt(2)));` ?
