### ISSUE TITLE
V3.3.1 SCSS has compilation issues

### ISSUE THREAD

**Issue by aaitmouloud** [Orange-OpenSource/Orange-Boosted-Bootstrap#20]
Hello,
I'm using V3.3.1 of Boosted.

When trying to compiles the files present at "app/scss", i have the following error:

```
Error: Invalid CSS after "      .clearfix": expected "{", was ";"
        on line 476 of <...>/target/generated-sources/scss/bootstrap/_orange-css.scss
        from line 21 of<...>/target/generated-sources/scss/boosted2015.scss
```

This seems to be related to this line, shouldn't it use `@extend` or `@include` ?
 https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v3.3.1/app/scss/bootstrap/_orange-css.scss#L476

Anyway, this issue seems to be still present in `master` (https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/master/app/scss/bootstrap/_orange-css.scss#L522)

Thank you.

**Comment by Lausselloic** [comment]
Hello,

I've pushed a fix for this bad mixin conversion on master branch. Can you try it, and confirm that it solved the problem for you?

**Comment by aaitmouloud** [comment]
Hi, 

Thanks for the quick answer.

I can only test the `scss `part of the fix, and that part compiles and works : **OK**. 👍 
I do not have the tools to test the `less` partn sorry about that.

As far as i'm concerned, this issue can be closed, expect if you want to be sure that the `less `part is OK too, i'll leave it to you.

**Comment by Lausselloic** [comment]
I've checked the less version wich is used to compile the native distribution.
