### ISSUE TITLE
Borders : add design callout messages

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#2062]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

-- TO DO --

**borders/#color**
- [ ] Add a design callout message saying that example 2 and 3 shouldn't be used.

**borders/#opacity**
- [ ] Add a design callout message saying that this variant shouldn't be used because no opacity allowed on borders. 
       FYI : the only exception is the pagination dot with an 50% opacity applied on white (won't be written in the design callout message.

**borders/#radius**
- [ ] Add a design callout message saying that the variants different from `rounded` and `rounded-pill` shouldn't be used.

**borders/#sizes**
- [ ] Add a design callout message saying that the variants different from rounded-0 (= square corners) shouldn't be used.

### Motivation and context

This issue is part of the work done in issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1199 and its PR https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1614. This issue concerns the Border component reviewed with design and dev to identify where to add design callout messages and where to modify Boosted doc.

**Comment by Dojacom** [comment]
Hi!
Is this issue still open? How can i help in contributing?

**Comment by julien-deramond** [comment]
Hi @Dojacom 
This issue has already a corresponding PR.
