### ISSUE TITLE
Borders : fix design

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#2063]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

-- TO DO --

**borders/#color**
- [ ] In this example ![image](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/89514509/3fd50ba5-a9e1-46a6-9ff8-f60ff12c667c) 
    - [ ] In the `Email address` example, change the present green border color by our Orange functional red for light background which is #cd3c14

### Motivation and context

This issue is part of the work done in issue https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1199 and its PR https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1614. This issue concerns the Border component reviewed with design and dev to identify where to add design callout messages and where to modify Boosted doc.

**Comment by julien-deramond** [comment]
Closing it since we'll keep those examples as-is and display a design callout in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2064
