### ISSUE TITLE
Use master as main branch, including v5

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#207]
- [x] keep v3 in v3-dev
- [x] keep v4 in v4-dev
- ~~rename `master` to `main` to follow-up Bootstrap (outdated?)~~
- ~~change `build/ship.sh` to pull `main` instead of `v4-dev`~~
- ~~what else?~~

**Comment by ffoodd** [comment]
To do on v5.0.0 release.

**Comment by julien-deramond** [comment]
- [ ] Rename `v5-dev` to `main` to follow-up Bootstrap
  - https://github.com/github/renaming
  - https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch
  - ℹ️ Tried it on a private repo and the Pull Requests are well updated but ⚠️ on references in files like GitHub CI configurations
- [ ] What's in `master`? Should we keep it?

**Comment by Nurovek** [comment]
> * [ ]  Rename `v5-dev` to `main` to follow-up Bootstrap
>   
>   * https://github.com/github/renaming
>   * https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch
>   * ℹ️ Tried it on a private repo and the Pull Requests are well updated but ⚠️ on references in files like GitHub CI configurations
> * [ ]  What's in `master`? Should we keep it?

I guess master was the default branch in the v3 era ? I didn't see it being used after 3.4.1 release 🤔

**Comment by julien-deramond** [comment]
`v3-dev` and `master` are at the same level. So we can remove `master` branch.

![v3-master](https://user-images.githubusercontent.com/17381666/131960272-53ae0c5e-ecd8-41fb-98e8-2316bff17aa7.png)

**Comment by ffoodd** [comment]
Yup, Bootstrap uses `main` (previously `master`) for the current version. Boosted chose to go with `v4-dev` instead, then `v5-dev`; so `master` stopped being updated when v4 started.

I don't know why 🤷

**Comment by ffoodd** [comment]
FYI moving from `master` to `main` on Bootstrap required to manually update PR targets, but non GitHub has a dedicated feature that's supposed to work out if the box.
