### ISSUE TITLE
Contrast enforcement widget

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#209]
As seen on [oui.sncf](https://oui.sncf) for example, a simple switch component would let us increase contrasts that are known to be low.

Oranges are particularly sensitive.

**Comment by ffoodd** [comment]
[Tanaguru has a dedicated repository](https://github.com/Tanaguru/contrast-switcher).

**Comment by julien-deramond** [comment]
Closing it by referencing these comments in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/510. Would be tackled at the same time.
