### ISSUE TITLE
[SCSS] icon-font-path variable in boostedIcons

### ISSUE THREAD

**Issue by aaitmouloud** [Orange-OpenSource/Orange-Boosted-Bootstrap#21]
Hello,

In https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/master/app/scss/bootstrap/_boostedIcons.scss#L5 the `$icon-font-path` variable is not set correctly for the '`boosted`' font, and it is not correctly compiled.

The cause in my opinion is that it is inside a string, and thus, it should have brackets as follows:

```
@at-root {
  @font-face {
  	font-family: 'boosted';
  	src:url('${icon-font-path}boosted.eot');
  	src:url('${icon-font-path}boosted.eot?#iefix') format('embedded-opentype'),
  		url('${icon-font-path}boosted.ttf') format('truetype'),
  		url('${icon-font-path}boosted.woff') format('woff'),
  		url('${icon-font-path}boosted.svg?#boosted') format('svg');
  	font-weight: normal;
  	font-style: normal;
  }
}
```

Thank you.

**Comment by Lausselloic** [comment]
Hello,

boostedIcons file recently added, and automatic conversion tool not updated. Sorry for that, I've fixed it, by adding the specific conversion font-path var in boostedIcons file.

I've test the scss build and now it's okay for me.

Let me know if the master branch solve the problem also for you.

**Comment by aaitmouloud** [comment]
Thanks a lot for the quick answer, this fixes the issue for me. I'm closing this issue.
