### ISSUE TITLE
Add links to new versions in menu

### ISSUE THREAD

**Issue by MewenLeHo** [Orange-OpenSource/Orange-Boosted-Bootstrap#2111]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Add links to the 5.2 version and to the incoming v5.3 in menu:

![versions](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/92363071/4c3a6bd2-17d1-44c9-850e-9fad33ad429f)

### Motivation and context

Promote newest versions of Boosted to users still in v4.x.x.

**Comment by julien-deramond** [comment]
Might be difficult to maintain (for the versions list) and to backport in previous versions, but we could at least just display a banner like Bootstrap:

![Screenshot 2023-06-29 at 10 42 25](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/17381666/cba255d5-1c4a-4201-bac5-8e045a7712ca)

For example in https://getbootstrap.com/docs/4.6/getting-started/introduction/

I can do that while I'm backporting https://github.com/twbs/bootstrap/commit/87498ceeb2c9c0961e83caca5e13c58f9d554a5f into Boosted

**Comment by julien-deramond** [comment]
What's been mentioned in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/2111#issuecomment-1612645115 has been released (see https://boosted.orange.com/docs/4.6/getting-started/introduction/). Can we close this issue?

**Comment by MewenLeHo** [comment]
Looks good to me so I am ok to close this issue.
