### ISSUE TITLE
Design callout messages: make included links accessible

### ISSUE THREAD

**Issue by isabellechanclou** [Orange-OpenSource/Orange-Boosted-Bootstrap#2128]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Design callout messages often contain links towards the DSM and/or some other Boosted component.
Their accessible name (to be vocalized by screen readers) needs to be added/completed to indicate the target of the link, and mainly when a same wording is used for the different targets as it is the case in the Boosted badge component:

![image](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/89514509/7aa5e1e2-dab9-439c-863c-8724faa016a5)

A way is to be find to add in the code to add this accessible name. The code is written this way:

```
{{< design-callout-alert >}}
This component should not be used because it does not exist in the Orange Design System specifications.
Instead, consider using our Boosted [Tags]({{< docsref "/components/tags" >}}). You can also refer to the [Tags](https://system.design.orange.com/0c1af118d/p/975c09-tags/b/24dde8) guidelines on the Orange Design System website.
{{< /design-callout-alert >}}
```

Hint to try if compatible with the above syntax : adding some html `<span>` with a `title` attribute...

### Reduced test cases

NA

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What version of Boosted are you using?

v5.3

**Comment by MewenLeHo** [comment]
Possible option: since HTML is allowed inside markdown, simply use an HTML `a` tag for links instead of md links. Then use `title` or `aria-label` attributes to make it accessible.
