### ISSUE TITLE
[Tracking] Dark mode

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#2140]
This issue tracks dark mode reverts we'll need to do when the dark mode will be implemented:
- Check modifications in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2030 (most of the one linked to the text colors must be reverted)
  - https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2030/commits/214f1d0057e106f3333179ca38be4932c6e9ec2a
  - https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2030/commits/8b46e1f116c8868d9138bcdd511c770e8e97bb02
  - TODO: add others
- https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2034#pullrequestreview-1528213073
- Think to modify https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2158/commits/983d0eb36d96e6508a7c9520a1b3814a10f29263 if needed
- Revisit this Bootstrap section (https://getbootstrap.com/docs/5.3/components/navbar/#color-schemes) in Boosted which is hidden for now but could work when we'll get rid of `.navbar-dark` and replace it with `data-bs-theme="dark"`

**Comment by Dojacom** [comment]
Hi there.
How can i help on this case?

**Comment by julien-deramond** [comment]
Hi @Dojacom 
This one will be handled by the Boosted core team because it needs to know the complete history of the recent modifications + discussions/specifications with Orange insiders.
