### ISSUE TITLE
Remove dark mode on download apps example page

### ISSUE THREAD

**Issue by MewenLeHo** [Orange-OpenSource/Orange-Boosted-Bootstrap#2181]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The dark mode was removed for the newest releases.
Because of that, in the dowload apps example page (https://boosted.orange.com/docs/5.3/examples/download-app/), we have at the same time images from the light AND dark mode:

![screenshot-boosted orange com-2023 07 28-16_12_04](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/92363071/703cf992-f418-463a-ad62-1599d36e4360)

It's working but it looks confusing.

### Reduced test cases

Go to https://boosted.orange.com/docs/5.3/examples/download-app/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Boosted are you using?

v5.3.1

**Comment by julien-deramond** [comment]
Fixed via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/f9fcefeba442d2da7c3dd7e7fb6aeecc612de28a
