### ISSUE TITLE
Drop 'Twitter' and introduce 'X'?

### ISSUE THREAD

**Issue by MewenLeHo** [Orange-OpenSource/Orange-Boosted-Bootstrap#2182]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

According to recent news, 'Twitter' (https://twitter.com/) has been rebranded to 'X'.

![screenshot-publish twitter com-2023 07 31-09_33_31](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/92363071/a7bae7d7-9f54-4664-ae15-cc7137c7903f)

Actually it looks like a bit messy and it's still not clear if it is temporary or not. I don't even know if we still legally have the right to use the name 'Twitter' and/or the logo with the bird inside Boosted's documentation:

![twitter](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/92363071/08c999b8-9013-4b9e-ab41-040e8800429d)

### Motivation and context

What are your thoughts on this?
Is there a need to do something here?
Should we keep the social button with the bird only? Replace it by a 'X' button? Or maybe keep both alternatives?

@B3nz01d @julien-deramond @CyriaqueBillard @Franco-Riccitelli

**Comment by MewenLeHo** [comment]
https://www.reuters.com/technology/problem-with-x-meta-microsoft-hundreds-more-own-trademarks-new-twitter-name-2023-07-25/
https://www.politico.eu/article/twitter-x-trademark-regulations-logo-european-union-elon-musk/

The name may change again soon so it's probably better to wait before making any change.

**Comment by Franco-Riccitelli** [comment]
It looks like the "X" has replaced the bird as the new logo ... for now.
Attached is how it would look in our social button style with the different states.
I've also attached an SVG of the X logo at the correct size for our social buttons.
I've kept the same blue colour for the hover state as this is still used by Twitter.

<img width="255" alt="Screenshot 2023-08-01 at 4 04 06 pm" src="https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/76205386/eac3621e-b708-42f3-80c8-73518792d2fc">

SVG of the Twitter X logo

![Twitter X](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/76205386/64942c1a-be63-4bb9-94cf-8ac68909818c)

**Comment by julien-deramond** [comment]
For reference, it was asked by the community and projects via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/2643.

Now, the name is officially X and is used almost everywhere.

Some websites still prefer to display Twitter anyway for now.

So let's keep Twitter social button for a while, and add the X one too in our social buttons.
