### ISSUE TITLE
Import error webpack

### ISSUE THREAD

**Issue by MaximeChartier** [Orange-OpenSource/Orange-Boosted-Bootstrap#220]
Hey ! 

I want import boosted in my Nuxt project.

``` bash
  "dependencies": {
    .
    .
    "boosted": "^4.3.1",
    "jquery": "^3.4.1",
    "popper.js": "^1.16.0"
    .
    .
  },
```
When I import "boosted" in my code i get return this error
``` bash
Cannot set property 'emulateTransitionEnd' of undefined
```

Thanks

**Comment by Johann-S** [comment]
Hi @MaximeChartier,

Bootstrap and jQuery must access to the `window` object, it seems it's not possible according to your error.
I think this post can help you: https://kaloraat.com/articles/how-to-use-jquery-in-nuxtjs

**Comment by ffoodd** [comment]
Hi @MaximeChartier, did @Johann-S answer help? 
If so, would you please close this issue? Otherwise, please tell us more about this issue.

Thanks!
