### ISSUE TITLE
Documentation website: complete review

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#225]
It would be great to improve the documentation website in upcoming v4.4.0:

- [x] remove useless specific styles coming from Bootstrap
- [x] double-check Boostwatch;
- [x] browser compat: 
   - [x] Firefox
   - [x] IE11
   - [x] Firefox ESR
   - [x] Chrome
- [x] ensure [Orange accessibility recommandations](https://a11y-guidelines.orange.com/) are followed and applied (eg. labelling multiple `nav`)

What else?

**Comment by notabene** [comment]
re: “ensure Orange accessibility recommandations are followed and applied”

Add comments in template HTML for components.

For instance: 

> The `nav` component should have an `aria-labelledy` attribute if there is more than one `nav` in the page. If there is only one, you can leave as-is.

(plus an implementation example, maybe)
