### ISSUE TITLE
cards are messed up

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#23]
Some card variants are broken [in Boosted](http://boosted.orange.com/v4-alpha/components/card/) whereas [Bootstrap's ones are good](http://v4-alpha.getbootstrap.com/components/card/).

This component would be very helpful for content centric websites using Boosted.

**Comment by Lausselloic** [comment]
Hello,

Yes we've seen it on v4-alpha.4. It have been fixed in v4-dev branch target release next alpha.
You can check it on the pre-release test url : http://boosted.orange.com/v4-test/components/card/
