### ISSUE TITLE
Remove references to Bootstraps core team

### ISSUE THREAD

**Issue by MartijnCuppens** [Orange-OpenSource/Orange-Boosted-Bootstrap#237]
Hi there!

Could you remove the references to the Bootstrap team members here? https://boosted.orange.com/docs/4.3/about/team/

**Comment by ffoodd** [comment]
Yes, of course! Thanks for pointing this :)

**Comment by Lausselloic** [comment]
Maybe keep a link to getbootstrap page? At the begening I keep that page to keep team property, but yes we could remove from there.
