### ISSUE TITLE
Megamenu "back to menu" label

### ISSUE THREAD

**Issue by cedricescarment** [Orange-OpenSource/Orange-Boosted-Bootstrap#247]
Hello,

I use boosted 4.3.

In the megamenu :
https://boosted.orange.com/docs/4.3/examples/news-template/

Boosted generate an alternative aria label for the mobile "back to menu" buttons.

We can translate this label for non english website.

In version t's seems to come from : 

```
var goBackLabel = "go back to " + $topMenu.text() + " menu";

if (!$topMenu.length) {
          goBackLabel = "go back to " +                     
          $(this).closest(Selector$5.MEGAMENU_PANEL).prev(Selector$5.NAV_LINK).text() + " menu";
}
```

**Comment by ffoodd** [comment]
Somewhat related to #228 :)
