### ISSUE TITLE
Missing Fonts

### ISSUE THREAD

**Issue by danygit** [Orange-OpenSource/Orange-Boosted-Bootstrap#25]
HelvNeue55 and HelvNeue75 are available but HelvNeue65, HelvNeue45 and HelvNeue35 are missing.
Could you add it ?

**Comment by Lausselloic** [comment]
Fonts other than Helvetica Neue 55 roman and Helvetica Neue 75 bold are no more allowed by the Orange brand. That's why we don't provide it into the Boosted core
