### ISSUE TITLE
Dropdown component with search feature 

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#2513]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hi @julien-deramond 
I'm coming back to news about that component as I remind (cf.  #943 and #1123) that you were working on that kind of component but was not yet available in v5.2.

Do you have some news if it could be released in future version ?
If not, i'm fearing that we will have to do a custom development as we need more and more that kind of component (for enhancing customer experience regarding long list of districts for example, for selecting a country, etc.).

Thanks for your feedback

### Motivation and context

We are actually needing this dropdown for several type of contexts in use of MEA portals notably (but not only).
For example : in roaming, rather than having a long list (not very suitable in mobile), we would like to enhance the customer experience by permitting him to type the first letter of a country and easily selecting it
Another example is in eShop funnel where user should select his district in a long list of districts proposed.
There are also examples depending context and country needs.

**Comment by julien-deramond** [comment]
> Do you have some news if it could be released in future version ?

We haven't planned yet the future components to embed into Boosted. It's one of the components we'd like to continue working on now that the dark mode is released. More information will come in #943 or the corresponding PR when it is started.

> If not, i'm fearing that we will have to do a custom development as we need more and more that kind of component (for enhancing customer experience regarding long list of districts for example, for selecting a country, etc.).

You have maybe some starting points in the #943 discussion as we prototyped some stuff in the past. Apparently, you'll start the development before us, so if you manage to do something, please don't hesitate to share it in #943. Even if it's not directly reusable, it could help.

I'm going to close this issue as duplicate and mention it in #943 as a reference for your need. #943 is already tagged as "asked by community" for priority management on our side.
