### ISSUE TITLE
Menu items letters drop to second row on smaller screens (~768px)

### ISSUE THREAD

**Issue by OriginalUserName** [Orange-OpenSource/Orange-Boosted-Bootstrap#2552]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On smaller screen resolutions (for example 768px - tablets), or if you zoom in on the page, menu items letters drop to a second row. The issue is visible on [orange.com](https://www.orange.com/fr) and also on the Brand Site : [brand.orange.com](brand.orange.com)

![menu](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/3025982/9ad2db58-c414-48d0-98e7-8ef3751e4e77)

### Reduced test cases

brand.orange.com
orange.com

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Boosted are you using?

5.3.2

**Comment by julien-deramond** [comment]
Thanks for reporting this issue @OriginalUserName 
I've created a CodePen with your menu based on the Orange navbar provided in our documentation for Boosted v5.3: https://codepen.io/julien-deramond/pen/YzMgeoe.
The nav links should appear only from 1024px. At 768px, here's the rendering:
![Screenshot 2024-04-26 at 16 05 37](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/17381666/3a75ac8b-0c49-405b-ab7f-fbd3df32a00c)
![Screenshot 2024-04-26 at 16 05 30](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/assets/17381666/a0b581ca-8b97-4498-84e1-0759edc22176)

Could you please double-check your DOM and the classes used? It's possible that they are not updated.

**Comment by OriginalUserName** [comment]
Hi @julien-deramond,

We can see this issue happening on live orange.com website as well. Does that mean they aren't using the proper classes as well? We have a similar integration on the Brand Site.

**Comment by julien-deramond** [comment]
Yes, it looks like the DOM and classes from both websites is closer to Boosted v4 (with the Orange megamenu) than Boosted v5.
For example, I can spot at least the usage of `.navbar-expand-md` which is now `.navbar-expand-lg`.

**Comment by OriginalUserName** [comment]
Hi @julien-deramond, we are using the class navbar-expand-lg on the Brand Site, so that means we should be using the correct markup for Boosted V5?
