### ISSUE TITLE
Strange url of fonts ?

### ISSUE THREAD

**Issue by mbrechet** [Orange-OpenSource/Orange-Boosted-Bootstrap#26]
Hi,

Can you explain the parameter `?aaqub7` in font src ?
This strange parameter cause my webpack build failed.
I'll try to fix the build but I'm insterested in an explanation of this parameter.

Regards

**Comment by ygatesoupe** [comment]
Hi,

This character set is used in font url to prevent browsers from loading an older version of the icons. Each new delivery of the icon set will have a different character set in its url.

Webpack may not recognise or expect these characters so might need to change the loader test regex
