### ISSUE TITLE
[OUDS] Tokens: Typography

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#2645]
## Description

The aim of this issue is to study and implement the typography tokens taking into account the cohesive multi-platform approach, the customization by libraries inheriting OUDS Web, but also what we're using for OUDS Web: Boosted, Bootstrap etc.
- Define the possibilities
- Define the constraints
- Define the impacts
- Implement the tokens (with a future Style Dictionary usage in mind)

Reminder: there will be in the end 3 layers of tokens:
- **Raw primitive values: Insertion of brand foundations.**
  - These tokens will be customizable by libraries inheriting OUDS Web.
  - These tokens cannot be used by developers using OUDS Web.
- **Semantic applications: Depends on raw primitive values.**
  - Mapping between these tokens and the raw primitive values will be customizable by libraries inheriting OUDS Web.
  - These tokens can be used by developers using OUDS Web.
- **Component applications: Depends on semantic applications.**:
  - Mapping between these tokens and the semantic tokens should rarely be customized by libraries inheriting OUDS Web.
  - These tokens can be used by developers using OUDS Web.
  
### Raw primitive values

* TODO: fill

### Semantic applications

* TODO: fille

---

## Study

- [ ] Study the architecture of these tokens, and define the technical details

### Technical details

TODO

**Comment by louismaximepiton** [comment]
Closed by #2774.
