### ISSUE TITLE
Get rid of `focusable="false"` for decorative `<svg>`s

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#2677]
### Description

Decorative SVGs are most of the time used like this: `<svg aria-hidden="true" focusable="false">` in Boosted.
`focusable="false"` was there for a better support for Internet Explorer.
IE being not supported anymore, can't we get rid of `focusable="false"` in those cases, knowing that it's already the case for Bootstrap (see https://github.com/twbs/bootstrap/commit/ac831aa4df8e817883c1510f74604ea67e26f179#diff-17bd0a43dcea923cbb44c877ce1462c41b5624ccafa66f29cb6d0946707f096c)

**Comment by Aniort** [comment]
ok, u can !
