### ISSUE TITLE
Font bold on safari

### ISSUE THREAD

**Issue by danygit** [Orange-OpenSource/Orange-Boosted-Bootstrap#27]
Set font weigth to bold in safari is not enough.
it should add -webkit-font-smoothing: antialiased;  on b and strong tag

**Comment by ygatesoupe** [comment]
Fixed in commit ff695de3d.

Could you confirm this is working for you ?

**Comment by danygit** [comment]
It's ok but take care about comments with // in sass file.
Thanks

**Comment by ygatesoupe** [comment]
Both comment styles are supported on less or sass files

**Comment by danygit** [comment]
Of course but not in css files. 
But when you use basic method to transform sass to css, // is not understand.
We should us plugin to remove this comments.

/* works without additional plugins.

**Comment by rudzboy** [comment]
Hello, double slashes in CSS are NOT a good practice for many reasons, the second answer on that post in pretty straight-forward : http://stackoverflow.com/questions/12298890/is-it-bad-practice-to-comment-out-single-lines-of-css-with
Must be avoided at all costs (for now) ;)
