### ISSUE TITLE
Will Orange-Boosted-Bootstrap support bootstrap 5?

### ISSUE THREAD

**Issue by heithemmoumni** [Orange-OpenSource/Orange-Boosted-Bootstrap#275]

**Comment by ffoodd** [comment]
Yes, it will: as you may see in ["v5" project](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/projects/7) or in [issues tagged "v5"](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?q=is%3Aissue+is%3Aopen+label%3Av5).

However we're still polishing our last v4 to ensure it stays  stable and up-to-date before going on v5 :)
A matter of weeks, probably :)
