### ISSUE TITLE
Phone number field in Boosted ?

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#2810]
### Prerequisites

- [x] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Good day
I'm searching an example in Boosted that I could refer to developers to illustrate the correct use of a phone field with country selector.
In Design System we have apparently this that might be used for forms : https://system.design.orange.com/0c1af118d/p/88ab5b-forms/b/599459/i/48901789
![Image](https://github.com/user-attachments/assets/e7b511be-6cfe-4d63-91b4-aef200c9bee5)
Do you have also - if not yet existing in Boosted - a recommendation regarding library to use/good practice ?

### Motivation and context

We are currently reviewing some journeys related to eShop funnel.
In those funnels, we are currently asking in most of cases for local/national number... but with eSims we need to consider possible tourists/diaspora that might not have a local contact number and need to fill in a foreign number.

**Comment by louismaximepiton** [comment]
Hello @MathieuPomm,

I don't think we have more information than you about this subject. For instance, as a starting point, I would go for https://github.com/jackocnr/intl-tel-input that seems quite close to what we want in Orange.
If you find any other cool open-source library about this subject, feel free to write it down somewhere around here and maybe explain how you implemented it.

**Comment by MathieuPomm** [comment]
Thanks @louismaximepiton (ans sorry for the answer delay).
After confirmation, we are already using this library in our portals (for forms), so thanks for confirmation, we will pursue to use it, notably in funnel.
Do not hesitate to let us know when this component might be available in Boosted (if it will be).

We could consider this request treated
Brgds
