### ISSUE TITLE
[SCSS] Tooltip styles not present when compile SASS files

### ISSUE THREAD

**Issue by aaitmouloud** [Orange-OpenSource/Orange-Boosted-Bootstrap#29]
When compiling the sass files present at https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/tree/master/app/scss, the `tooltip` styles are not present in the resulting CSS.

This is because these styles are not present in the following file: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/master/app/scss/bootstrap/_tooltip.scss

Example of missing styles: 

- `.tooltip-arrow`
- `.top`
- `.top-left`
- ..

Thank you.

**Comment by Lausselloic** [comment]
Hello,

Yes sorry for that. 
I've pushed a fix onto master branch, can you try again?

**Comment by aaitmouloud** [comment]
Using the master branch, the problem is solved for me.
