### ISSUE TITLE
Border spinner colors

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#318]
Operating system: macOS
Browsers:
- Chrome (Version 79.0.3945.130)
- Firefox (73.0 (64 bits))

We can see in https://boosted.orange.com/docs/4.4/components/spinners/#colors that colors are not applied to border spinners.

I tried the following code in my project where the text colors are neither applied so it can maybe explain the problem related to the border spinners colors:
```html
<p class="text-success">.text-success</p>
<p class="text-danger">.text-danger</p>
<p class="text-warning">.text-warning</p>
<p class="text-info">.text-info</p>
```

**Note**: There's no problem in the 4.3 Boosted version (https://boosted.orange.com/docs/4.3/components/spinners/#colors)

**Comment by ffoodd** [comment]
Hi there,

Nice catch! You're right in that it's `.text-*` related.

It's related to [this commit](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/1ecdbe01bde815aaebce34ba802cc779e2f9ce55) in v4.4.1 (document in Features / Colors and Icons in [v4.4.1 changelog](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/tag/v4.4.1).

As a matter of fact, those colors are simply forbidden by the Orange Brand **for text**.

I guess I can take colored spinners back by extending them with those `.text-*` classes. I add this to the v4.4.2 roadmap :)

**Comment by ffoodd** [comment]
Sidenote here, just to mention that this behaviour will change again. The design guidelines implemented spinners, and they now have the same color restrictions than text…
