### ISSUE TITLE
No space between badge and text in a button

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#319]
Operating system: macOS
Browsers:

    Chrome (Version 79.0.3945.130)
    Firefox (73.0 (64 bits))

We can see in https://boosted.orange.com/docs/4.4/components/badge/ that there is no space between the badge and the text inside a button.

It seems that it comes from the following commit https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/3a18fbfabc7359f0a678bfb728b5b11c0a912a68#diff-8a4fc4262c9197c73b80fb80d8863ae5 where `display` has changed for the class `.btn` in _scss/_buttons.scss_:
```diff
.btn {
-  display: inline-block;
+  display: inline-flex; // Boosted mod
``` 

Note: There is no problem in the 4.3 Boosted version (https://boosted.orange.com/docs/4.3/components/badge/)

**Comment by ffoodd** [comment]
That's right, by using `inline-flex` for `display`, button's content is not considered as text anymore but as flex items.

Should be fixed by a `margin`, thanks!
