### ISSUE TITLE
Megamenu exemple cause a js crash

### ISSUE THREAD

**Issue by cedricescarment** [Orange-OpenSource/Orange-Boosted-Bootstrap#329]
The exemple in the page :
- https://boosted.orange.com/docs/4.4/components/orange-megamenu/#usage
use a css class "collapsed" on a simple link of the first level : 
`<a class="nav-link collapsed" href="#" data-toggle="collapse">My Orange</a>`

Using this css class cause a javascript crash when the href is a link and not an anchor.

Same issue on the page : 
- https://boosted.orange.com/docs/4.4/examples/news-template/

Suggestion : delete "collapsed" css class on the first level when item have no child.

**Comment by Lausselloic** [comment]
The collapsed class need to be added by the plugin, it's a mistake to have it in the source code. But for this case, need to remove data-toggle="collapse" on link that doesn't have submenu

It's a bug in the example not in the plugin itself
