### ISSUE TITLE
Boosted-flex not using flexbox…

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#33]
Current boosted-flex' grid in V4-dev isn't using flexbox (still floating).

I had a look to scss files and I don't get it, $enable-flex is set to true, _variables.scss has a !defautl flag so it should work :/

Any idea?

**Comment by Lausselloic** [comment]
Yes we have force the value in _custom.scss. But don"t worry, bootstrap alpha.6 (latest alpha before the beta) is closed to be launch and flexbox will be the default mode of bootstrap 4.

We will try to check in our _custom.scss if some value really need to be locked or if it's better to preserve a !default flag for them.

**Comment by ffoodd** [comment]
Thanks :) Flexbox could help a lot in many ways.
