### ISSUE TITLE
Focus in Orange Megamenu and Orange footer is not visible

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#35]
Simply due to outline being defined for every link with a black color, except for `.navbar .nav-item .nav-link` as far as I can see.

May I suggest to remove `#000` in `a:focus { outline: 1px dotted #000; }` (which would fallback to `currentColor`) and stop overriding any outline?

This way the single `a:focus { outline: 1px dotted; }` would apply a correct outline to every link (assuming that links have sufficient contrast ratio, obviously) and we would save a few declaration block.

What's your opinion?

**Comment by Lausselloic** [comment]
Yes for sure it's a good idea! 
Just create orange outline for branded text but outline is stille present, and that's the key point!

I will push a fix for the next release
