### ISSUE TITLE
Forms icons - feedback

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#354]
Bonjour,

Les tailles des icônes ne semblent pas homogènes concernant les feedbacks de validation des formulaires.
Ceci est visible sur le site Boosted : 
https://boosted.orange.com/docs/4.4/components/forms/#how-it-works

Screenshot : 
![image](https://user-images.githubusercontent.com/63303383/78683376-7db8c780-78ef-11ea-8449-4ebc0e30ec23.png)

**Comment by ffoodd** [comment]
Bonjour,

Pourriez-vous m’indiquer sur votre navigateur et sa version ?

**Comment by MathieuPomm** [comment]
Bonjour

cela a été testé sur 
- Firefox 68.6.1esr
- IE 11
- Navigateur mobile Samsung (Android)
