### ISSUE TITLE
Modal - problème de display

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#355]
Bonjour,

Nous avons constaté qu'avec la nouvelle version, un translateY(-50px) est susceptible de perturber l'affichage d'une modale, notamment sur mobile où il devient impossible d'accéder au "haut" de la modale.

cf. https://boosted.orange.com/docs/4.4/components/modal/#vertically-centered

![image](https://user-images.githubusercontent.com/63303383/78685068-87dbc580-78f1-11ea-9aad-b7351b134ad1.png)

Merci pour votre retour sur comment adresser ce souci.

**Comment by ffoodd** [comment]
A priori il suffit de modifier la valeur de `$modal-show-transform` dans `_variables.scss` pour le mettre à `none` plutôt que `null`.

Ce sera livré dans la prochaine v4 — mais si vous êtes en capacité de compiler vous même le Sass, je vous suggère de modifier cette variable dès maintenant :)

**Comment by MathieuPomm** [comment]
Merci @ffoodd pour ton retour.
Nous allons tenter de le faire de notre côté donc.

Pour information, peux-tu me préciser à quelle date approximative est prévue la prochaine v4 ?

**Comment by ffoodd** [comment]
D’ici quelques semaines a priori — mais nous dépendons directement de Bootstrap pour les publications de version.

En revanche selon la méthode utilisée pour appeler Boosted, vous pourrez peut-être cibler un commit plutôt qu’une version (NPM le permet, par exemple).

**Comment by MathieuPomm** [comment]
OK merci pour tes précisions et ton aide !

Je te propose de clore ce ticket.

**Comment by ffoodd** [comment]
Ah ah merci mais je le rouvre, ici le souci n’est pas corrigé :D

**Comment by MathieuPomm** [comment]
Désolé...
Après discussion en interne, nous utilisons les CDN de Boosted afin d'externaliser les ressources.
Nous allons réaliser un fix CSS à court-terme... mais sommes preneurs de votre retour dès que ce souci sera corrigé (car le comportement du fix mis en place risque alors de ne plus être correct).

**Comment by ffoodd** [comment]
@MathieuPomm La règle à ajouter (qui sera générée par le fix) est la suivante : 

```css
.modal.show .modal-dialog {
    -webkit-transform: none;
    transform: none;
}
```

Si vous appliquez uniquement ça, vous pourrez seulement enlever la béquille lors de la mise à jour :)
