### ISSUE TITLE
`<em>` tag doesn't put text in italic in v4.4 as it does in 4.3

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#365]
looks like a font impact, if I remove font-family, em text goes back in italic

**Comment by ffoodd** [comment]
Did you ever notice that Orange Brand Guidelines does not allow italicized text 😄?

FWIW it's because of `font-synthesis` I guess.

**Comment by ffoodd** [comment]
Confirmed, italic is forbidden by our brand. The only way to put an emphasis is the bold.

So unpopular question: should `<em>` be bold?
