### ISSUE TITLE
Dropdown in nav-item: arrow placement

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#37]
When using dropdown in navbar and if any HTML tag is inside the `.dropdown-toggle`, the caret absolute position goes to the left… Only on blink based browsers (Chromium, Brave, Vivaldi…).

Eg:
```
<a class="dropdown-toggle mt-0 py-2 pl-2" href="#" data-toggle="dropdown">
    Mon compte
    <span class="tag tag-pill tag-danger text-white">3</span>
</a>
```

I'm working with v4 alpha 5, BTW.

I'll fix this locally but that may be a dropdown bug (adding `right: .625rem;` to the `.dropdown-toggle::after` seems to do the job).

**Comment by Lausselloic** [comment]
Yes I've reproduce it on alpha.5
But not on alpha.6

Sorry for this alpha.5 bug, you'll need to keep your fix until upgrading to alpha.6

**Comment by ffoodd** [comment]
Looks good to me, I close this one :) 
Thanks!
