### ISSUE TITLE
Bootstrap's examples customization

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#380]
Examples are a great way to get projects started. However in v4, they weren't maintained on the Boosted side and pretty much unusable as-is.

We definitely should make them accurate from a brand perspective.

As a bonus, they may use our custom component at some point? Or would this be too much to maintain?

**Comment by Nurovek** [comment]
Snippets (examples) to "unbootstrapize" : 
- [ ] Headers (replace Bootstrap svg by Orange logo)
- [ ] Heroes (mentions Bootstrap)
- [ ] Features (make everything more squared)
- [ ] Sidebars (replace Bootstrap svg by Orange logo)

**Comment by Lausselloic** [comment]
Some more examples identified during beta3 merge
- [ ] Starter-template
- [ ] sign-in
- [ ] pricing
- [ ] jumbotron
