### ISSUE TITLE
v5 — migration guide

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#383]
Let's start some kind of Boosted's breaking changes when jumping from v4 to v5.

It'll need to be added to a migration guide: either to Bootstrap's one or by adding new page, like it was done between v3 and v4.

## Boosted v4 / v5

Ensure to add deprecation warnings in v4 when required (see #560 / #562 for examples).

- [ ] Didn't implement in both carousels and nav-tabs `> :last-child { margin-bottom: 0; }` to prefer using utilities
- [ ] Didn't implement `.navbar-brand + .navbar-brand`
- [ ] Dropped `$container-fluid-margin-widths`
- [ ] Badges stay in `em`, unlike in v4
- [ ] colors variables evolved to match UI Kit design tokens (refer to the doc): `$orange-2` changed to `$accessible-orange`, etc.
- [ ] new `$alert-icons` map (to document?) with icon handling
- [ ] Simpler close button, closer to bootstrap v5
- [ ] `$background-colors` replaces `$supporting-colors`
- [ ] Link with arrow (`.o-link-arrow`) is now link with chevron (`.link-chevron`)
  - `.back` has not been implemented since it's not part of the Web UI Kit. 
- [ ] Scroll-up (.o-scroll-up) is now Back to top (.back-to-top-wrapper and .back-to-top-link) and does not require any JavaScript anymore 🎉
- [ ] Social buttons now require `.btn-icon` modifier,
- [ ] Toggle buttons with icon: the pattern changed Bootstrap-side but we still require `.btn-icon` modifier too.
- [ ] Stepbar (`.o-stepbar`) is now Stepped process (`.stepped-process`) and all `.stepbar-...` classes are now `.stepped-process-...`
 - For Stepped process variables: 
   - `$o-stepbar-margin-r` is renamed `$step-item-margin-end`
   - `$o-stepbar-arrow-width` is renamed `$step-item-arrow-width`
   - `$o-stepbar-height` is not used anymore
   - Lots of new variables have been added aswell

### Color levels migration

If you were using `theme-color-level()` mixin or `$theme-color-interval` variable in your custom code in v4, those are gone in v5 and are replaced with new variables instead (as for grays in v4). Here's a compatibility table, using `$color` where it could be `$primary or any other theme color..

<details>
<summary>Color levels comparison table</summary>

| v4                                            | v5                  |
| --------------------------------------- | ----------------- |
| `theme-color-level($color, -8)` |  `$color-100` |
| `theme-color-level($color, -6)` |  `$color-200` |
| `theme-color-level($color, -4)` |  `$color-300` |
| `theme-color-level($color, -2)` |  `$color-400` |
| `theme-color-level($color)`      |  `$color-500` |
| `theme-color-level($color, 2)`  |  `$color-600` |
| `theme-color-level($color, 4)`  |  `$color-700` |
| `theme-color-level($color, 6)`  |  `$color-800` |
| `theme-color-level($color, 8)`  |  `$color-900` |

</details>

## Bootstrap v5 / Boosted v5

- [ ] **document Bootstrap parts dropped in Boosted**, somewhere
  - no `.floating-label`
  - no `.form-control-sm`, `.form-select-sm`, `.input-group-sm`, `.col-form-label-sm`
  - no forms' `.#{$state}-tooltip`
  - no `table-row-variants()`, `.table-bordered`, `.table-borderless`, `.table-striped`
  - no `.btn-outline`
  - no `.pagination-sm` nor `.pagination-lg`
  - no active state for `.list-group-item-action`
  - no floating labels
  - no carousel dark variant
- [ ] Alerts sizes & icons
- [ ] Nav Tabs light
- [ ] Responsive pagination with `pagination-max-items()`
- [ ] Progress sizes
- [ ] Spinners sizes
- [ ] Growing spinners
- [ ] `:focus-visible` is still here
- [ ] Tools: bots Mattermost & Slack, Percy, Pa11y, Calibre App ;
- [ ] Form validation: success and errors do not share the same layout, and icons aren't shown as inputs' `background`s
- [ ] Range input with filled thumb
- [ ] `color` and `background-color` utilities have their counter-part to ensure contrasts
- [ ] Introduced `target-size()` mixin
- [ ] Carousels:
  - [ ] animated progress indicator, introducing `--o-carousel-interval`, `.paused`, `.done` and `.static`
  - [ ] disabled controls when at one end and `data-bs-wrap="false"`
- [ ] Introduced `$boosted-variable-prefix` to supplement Bootstrap's `$variable-prefix`
- [ ] Link with chevron
- [ ] Back-to-top component
- [ ] Introduced `button-icon()` mixin
- [ ] Social buttons
- [ ] Icon buttons (alongside `.btn-icon` modifier)
- [ ] `.btn-no-outline` modifier
- [ ] Toggle buttons with icon

**Comment by julien-deramond** [comment]
Closing it as copied in #901
