### ISSUE TITLE
Range example - no orange color on mobile

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#385]
Hello

It might not be a bug but for information, it has been observed on mobile (notably on  Chrome browser and on Android browser) that the range example does not show "orange color".

cf. https://boosted.orange.com/docs/4.5/components/forms/#range

Please find a screenshot of the result for information : 
![image](https://user-images.githubusercontent.com/63303383/81961356-8ac58680-9612-11ea-98b2-e9f6981644cf.png)

**Comment by ffoodd** [comment]
Indeed, and it's mentionned in the "Progressive enhancement" callout just above the first example.

Only Firefox and legacy Edge currently supports filling tracks. On Android, you may want to check in Firefox.

There's nothing we can do in v4—and if ever we tackle this in v5, it'd be on  JavaScript side.

**Comment by MathieuPomm** [comment]
Oups... didn't see the progressive enhancement -_-.
Thanks for the details.
