### ISSUE TITLE
role="tab" should be direct children of role="tablist"

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#40]
At least that's what aXe says :)

I'm using Boosted V4 alpha 5 but the same markup is used in alpha 6.

I can't see [in any specification telling it *should* be direct child ](https://www.w3.org/TR/wai-aria/roles#tab) but they say it should whether be children or `aria-own`ed by `tablist`.

Not quite sure of what to do with this… Maybe programmatically populate an `aria-owns` attribute on `tablist`?

**Comment by Lausselloic** [comment]
Yes, aXe is right!

Fixed v4-dev

**Comment by notabene** [comment]
@ffoodd FWIW I often solve this problem using `role="decoration"`, what do you think?

**Comment by ffoodd** [comment]
`role="presentation"`, isn't it?
I don't know if it helps with aXe test, I may try next time I use it :)

**Comment by notabene** [comment]
> `role="presentation"`, isn't it?

Yeah sorry, posted too fast.

**Comment by notabene** [comment]
> `role="presentation"`, isn't it?

Yeah sorry, posted too fast.
