### ISSUE TITLE
Boosted skin for AdminLTE2

### ISSUE THREAD

**Issue by nabiltntn** [Orange-OpenSource/Orange-Boosted-Bootstrap#42]
Hi,
Is it possible to have an [AdminLTE2](https://www.npmjs.com/package/admin-lte) skin based on Orange Boosted ?

What we are doing now for one of our projects is to include [admin-lte](https://www.npmjs.com/package/admin-lte) npm package and copy manually the dist files from boosted ( potential version and fixes gap ).

I think i would be helpful for many projects to have just one optimized package available on NPM registery  ( let's say : boosted-adminlte ) that combines both.

**Comment by Lausselloic** [comment]
Hello,

Yes we have an AdminLTE skin but only for internal Orange company use at time. 
You can contact me by mail if you're working for Orange company.

**Comment by Lausselloic** [comment]
I'll close that question as won't do
