### ISSUE TITLE
Base-level rules connot contains the parent-selector the parent-selector-referencing character '&'

### ISSUE THREAD

**Issue by sk4ry** [Orange-OpenSource/Orange-Boosted-Bootstrap#44]
Hello,

I am using boosted v4-alpha.6.
I'm trying to use boosted theme including the boosted.scss into my main scss file.

On compiling i got an issue in the file node_modules/boosted/scss/_o-buttons.scss:272.

It seems that there is a '&' without parent at the end of this file.
Not sure if it's an issue or if i do something wrong

**Comment by sk4ry** [comment]
Hello,

Have you got an idea when the 6.1 will be release ?

**Comment by Lausselloic** [comment]
Hello,

I've no idea at time (maybe one or two weeks) we're working on core components.

But if you need the fix quickly, you can use the v4-dev tag instead of the v4-alpha.6. Which package manager did you use?

**Comment by sk4ry** [comment]
Ok thanks for the reply.
Actually i work on an orange project and discover this project. So i want to use v4 because it's corresponding on what we need.

I use npm as package manager.
