### ISSUE TITLE
Automatically add .text-break for '.form-group row's?

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#444]
In a `.form-group row`, the `<label>`s (most of the time) will be on the left part of the form.

Considering a multi language website, we can't control what text will be in those `<label>`s.

So we can be confronted to cases where the `<label>`s contain words very long in some languages; and we must add something like a `.text-break` class to handle it.

Because it's everywhere in the website, it seems that we have 2 choices:

- Change the global rule of `.form-group row` to automatically add `.text-break`.
- Add a `.text-break` everywhere manually.

Wouldn't be possible to automatically add the equivalent of `.text-break` for the `.form-group row`s directly in Boosted (or Bootstrap because it has the same behavior) or is it dumb? >> https://codepen.io/julien-deramond/pen/eYJKZmx.

The same thing is happening with `.form-control-plaintext`. Because you're not in control of what the user will enter, why not using automatically something like

```
overflow: hidden;
text-overflow: ellipsis;
```

Moreover, it works in Bootstrap 3 with `.form-control.static` (probably because it wasn't an `<input>`).

**Comment by ffoodd** [comment]
Indeed, that's a fair point—and I think it'd be better to ask for this in Bootstrap directly. Would you mind opening an issue to them, please?

**Comment by julien-deramond** [comment]
OK, I'll do it as soon as I can.
