### ISSUE TITLE
Orange Design System Accessibility changes to the Web UI

### ISSUE THREAD

**Issue by Chesnier-71** [Orange-OpenSource/Orange-Boosted-Bootstrap#446]
Bonjour, 
Les guidelines orange des boutons, et notamment du bouton orange ont changé en juillet 2020, le bouton reste orange, mais le texte doit passer du blanc au noir, 
Est il prévu de modifier ces boutons dans boosted orange rapidement ? En effet, ce bouton est présent sur la majorité des pages et/ou projets.
merci d'avance.

**Comment by ffoodd** [comment]
Évidemment, Boosted est une implémentation des _guidelines_ :D 

Il faut cependant se montrer patient, puisqu’il y a déjà des chantiers importants sur le feu et que, de toute façon, une sortie de version de Boosted est dépendante de son équivalent chez Bootstrap…

La prochaine v4 et la prochaine v5-alpha devraient toutes deux refléter ces nouveaux changements.
