### ISSUE TITLE
SideBar menu ?

### ISSUE THREAD

**Issue by StephaneG31** [Orange-OpenSource/Orange-Boosted-Bootstrap#45]
Hi all,
I work on a project with few main functionality for the main functionality (~7) for connected user to the service

Is there any design where website on "mobile view" have the same style than an Orange mobile App .
Any design inspired by "dashboard" : https://v4-alpha.getbootstrap.com/examples/dashboard/
In the last "Orange et moi" android app doesn't contain ay orange logo on the top left :
- left side bar menu (permanent on non "small" device, hidden on  "small" width device
- Hamburger menu (top left in place of Orange Logo) : visible only on "small" width device

Is there any convergence coming between App Guidelines and Browsing guidelines ?

**Comment by liyokuna** [comment]
Hello @StephaneG31 

Any update to add ? Did you find answers to your question ?
Otherwise, I'll close this issue.

BR

**Comment by StephaneG31** [comment]
You can close it, we made our custom menu ourselves and have made validate this design by Design Clinic Committee.

**Comment by Lausselloic** [comment]
Maybe there's a way to put it back into Boosted?

**Comment by StephaneG31** [comment]
Maybe for the concept but not for entire part of code because we doesn't
use boosted.

Cordialement,
Stéphane GIROUD
+33.6.89.08.26.39

Le mar. 2 avr. 2019 à 08:53, Laussel Loïc <notifications@github.com> a
écrit :

**Comment by liyokuna** [comment]
@StephaneG31 I will get to you soon for more details about it :) as @Lausselloic said it probably worth having it into Bosoted...
