### ISSUE TITLE
Add meta name="theme-color"

### ISSUE THREAD

**Issue by StephaneG31** [Orange-OpenSource/Orange-Boosted-Bootstrap#47]
Like GitHub make for Chrome on Android, add a meta 
<meta name="theme-color" content="#COLOR"> 
To provide a better experience on Orange Themes
https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/

**Comment by Lausselloic** [comment]
Hi,

You can add it directly in the projects. There's no recommendation in boosted for this.
