### ISSUE TITLE
Modals doesn't render properly on IE8

### ISSUE THREAD

**Issue by erodataM** [Orange-OpenSource/Orange-Boosted-Bootstrap#48]
![popin_ur jpg](https://cloud.githubusercontent.com/assets/1481432/23371454/7c1d1648-fd18-11e6-8420-ecf1ea86dc04.png)

1) close button (align left : right in rem + SVG doesn't work on IE8)
2) border bottom on modal-header
3) radios are not aligned

I fix it like that :
```
.fe_ie8 .modal .modal-header .btn {
    position: absolute;
    right: 10px;
    background-color: #FFF;
}
.fe_ie8 .modal-header {
    border-bottom: none;
}

.fe_ie8 .modal .modal-header .btn .close {
    background-image: url("/woopic/img/common/croix.png");
    height: 22px;
    width: 22px;
}

.fe_ie8 .o-radio {
    margin-top: -5px;
    margin-right: 5px;
}
```

**Comment by ygatesoupe** [comment]
Rem sizes fallback
Svg fallback 

fixed in commit ee04dcddc3fe909d0e7

There is no rules related to radio in modals
