### ISSUE TITLE
Documentation issue (code different than the DOM)

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#486]
Hello

It seems that the code proposed for the popin : https://boosted.orange.com/docs/4.5/components/modal/#orange-popin does not correspond to the example shown.

Notably, the code proposed does not include FLEX which are existing if we inspect the popin code.
![image](https://user-images.githubusercontent.com/63303383/93887059-7b53f980-fce6-11ea-826b-880cb45d30a5.png)

**Comment by ffoodd** [comment]
You're right, it's not using cards anymore. thanks for spotting this!

**Comment by MathieuPomm** [comment]
Sure, no problem :)
Could you please let us know when the code has been corrected on Boosted ?
Thanks in advance
