### ISSUE TITLE
JS Checkbox / Radio broken

### ISSUE THREAD

**Issue by yannbertrand** [Orange-OpenSource/Orange-Boosted-Bootstrap#49]
Firefox 40.0.1 on Ubuntu
Boosted@3.3.2

![boosted-checkbox-radio](https://cloud.githubusercontent.com/assets/5855339/23547244/c4e343ce-0002-11e7-9428-9edcda490c02.png)

**Comment by Lausselloic** [comment]
On all browsers, due to orange custom switch. http://boosted.orange.com/javascript/#buttons-checkbox-radio
