### ISSUE TITLE
Fail to install by Composer

### ISSUE THREAD

**Issue by vuzod** [Orange-OpenSource/Orange-Boosted-Bootstrap#52]
[RuntimeException]
  Could not load package orange-opensource/orange-boosted-bootstrap in http://packagist.org: [Un
  expectedValueException] Could not parse version constraint v4.0.0-alpha.3.1: Invalid version s
  tring "v4.0.0-alpha.3.1"

**Comment by Lausselloic** [comment]
Hello, the composer compliant version is not yet published (v4.0.0-alpha.6.1) could you try with v4-dev alias version "dev-master" ?

"require": {
    "orange-opensource/orange-boosted-bootstrap": "dev-master"
}

**Comment by Lausselloic** [comment]
v4.0.0-alpha.6.1 published. I close this issue, as I think the problem is now solved.
Please feel free to re-open it if the problem persist
