### ISSUE TITLE
Tabs behavior

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#527]
Hello

I have noticed (with Firefox) on Boosted with v4.5 that some tabs might have a different behavior : 
- for example "default" tabs titles are not underlined contrarily to "responsive" tabs.

Is this the expected behavior ? Shouldn't we have "all" titles (independently of the tab format chosen) underlined or not underlined ?

thank you for your inputs on that.

Considered page : https://boosted.orange.com/docs/4.5/boostwatch/#tab
![image](https://user-images.githubusercontent.com/63303383/96555016-8edb8b80-12b7-11eb-8781-a9e7455eba63.png)

Brgds

**Comment by ffoodd** [comment]
Indeed that's right! 
Seems related to [underlining harmonization that landed in v4.5.2 ](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/74fdd28c426dd3ed0df87f9db86647bbf64780ab), looks like I forgot those.

Thanks for report!
