### ISSUE TITLE
doc - toggle : add a warning on toggles to explain how to customize sizes

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#53]
http://boosted.orange.com/components/#toggles

For rounded toggles, add a warning to explain that user need to create a dedicated classe to customize the width depending onto the content

**Comment by ygatesoupe** [comment]
This has been fixed for v4 http://boosted.orange.com/4.0/docs/4.0/components/forms/#rounded
