### ISSUE TITLE
Creating a second menu "shop" on news example adds a space before the "back" link on mobile.

### ISSUE THREAD

**Issue by keoby** [Orange-OpenSource/Orange-Boosted-Bootstrap#536]
Booted v 4.5.
Mobile design
Megamenu

If i'm not mistaken, by adding a second menu "shop" on the megamenu in  the news example, the responsive design breaks on mobile. 
The "back" link is incremented by a "top" space because the first "shop" menu is just translatedX but still present in display. 
This prevents a second menu shop. Perhaps is it possible to change the first menu display when you change the style of the second in o-megamenu.js?

**Comment by ffoodd** [comment]
I'm not sure to understand, so let's define this more precisely. 
Would you be able to share some code example —maybe using [this CodePen template already using Boosted v4](https://codepen.io/pen?template=bGEVGPb)— or some screenshots?

**Comment by keoby** [comment]
Thanks for your reply.
Here is the codepen  [https://codepen.io/keoby/pen/JjKpmbd](url)
If you go to the second "shop" > "mobile" the back button is shifted on the top and the last link "accessories" disappears.

**Comment by ffoodd** [comment]
Spotted!
There was a useless `position: relative` which intercepted the absolute positionning of submenus. Easily fixed.
See [a forked CodePen used to diagnose](https://codepen.io/ffoodd/pen/YzWegzY) and a Pr is coming.
