### ISSUE TITLE
@font-face improvement

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#54]
As Boosted v4 officially only supports IE10+, we should remove `.eot`, `.ttf` and `.svg` from `@font-face` stack (both for Helvetica Neue and Orange Icons) — and delete associated files, of course. Please note that it'll also work with IE9.

It would result as a smaller package and a performance improvement since `.woff` is lighter and smarter than other formats.

Also maintaining files would be easier since there would be only two of them :)

**Comment by Lausselloic** [comment]
thanks @ffoodd
