### ISSUE TITLE
[Megamenu] Allow to open menu without moving focus

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#55]
For now we can't open megamenu specifying an active element without placing focus on it.

*This is perfect in a normal tabulation flow.*

But in our case, we're opening megamenu on the active item *on page load*, which should not place focus in active item, obviously.

I think the simplest way to go is to add a boolean parameter on the init method, to tell whether the script should place focus or not.

What do you think about it? Is there another way to go?

Ping @danygit

**Comment by sdeschamps-orange** [comment]
Hi @ffoodd 

Can you propose a patch that would do the following:

- Add a preference: boolean toggle to focus or not
- Set it to false by default in Boosted's default preferences
- Add a test at https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v4-dev/js/src/o-megamenu.js#L179

Thus:

- You have what you want and it won't break when Boosted upgrades
- By default nothing changes for the rest of the world

Thanks for your feedback

**Comment by Lausselloic** [comment]
available in boosted 4.0.1 see http://boosted.orange.com/docs/4.0/components/orange-megamenu/ for more informations
