### ISSUE TITLE
Tables line height in 4.5.2

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#594]
- Operating system and version: macOS (11.1)
- Browser and version (Chrome, Firefox, Microsoft Edge)

Since 4.5.2, Boosted provides a different default tables line height which seems to be a little bit too small.

- 4.5.0: https://codepen.io/julien-deramond/pen/bGwobBW
- 4.5.3 (and 5.*): https://codepen.io/julien-deramond/pen/OJRxLbb

**Comment by ffoodd** [comment]
Thanks for report!

After a few tests, it does not affect v5 → https://codepen.io/ffoodd/pen/LYRJzoZ
Going to tackle this on v4 though.

**Comment by ffoodd** [comment]
Just realized the current value is correct— thanks for reporting, though!
