### ISSUE TITLE
Helvetica ttf fonts don't seem valid

### ISSUE THREAD

**Issue by razvn** [Orange-OpenSource/Orange-Boosted-Bootstrap#6]
When trying to open:
**HelvNeue55_W1G.ttf** and **HelvNeue75_W1G.ttf** in windows preview an error message:  "Not a valid font file". 
This does not happen with others *.ttf of the project.

**Comment by Lausselloic** [comment]
Hello,

The Helvetica fonts provided in Boosted are only intended to be used for Orange websites.. See the NOTICE.txt for more informations https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/master/NOTICE.txt 


Neue Helvetica is a trademark of Monotype Imaging Inc. registered in the U.S. Patent and Trademark Office and may be registered in certain other juridictions
Orange Company has bought the right to use Helvetica for digital applications. 
You cannot use and distribute Helvetica font family unless explicitly authorized by Monotype Imaging Inc 

So, in our case, those files are provided as is by Monotype and can't be changed in any way.
