### ISSUE TITLE
Switches could be sizeable

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#60]
Using `em` instead of `rem`, switches could scale like other form controls using any `font-size` utilities such as `.small` or `.display-4` :)

At least, smaller switches would be great. Any objection?

**Comment by Lausselloic** [comment]
Hi, the switches size is defined by the Orange Brand and won't be smaller or bigger. Actual clicable area is 30px height (with the default font-size and zoom level), a lower clicable area would ask more effort to the user to be activated.

**Comment by ffoodd** [comment]
Too bad.
