### ISSUE TITLE
Something goes wrong on compilation (removing units on zero value)

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#62]
Watching at [this](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/db6b79ff3d90693f0077fab29deec8046fb79fcc/scss/_card.scss#L200), I see that the unit behind zero is present; however it is not, once compiled.

This cause some bugs on IE11, which needs the unit on `flex-basis` value :/

**Comment by ygatesoupe** [comment]
Hi there,

The code you're mentioning is part of native bootstrap. Could you readdress the issue to the bootstrap team ?

Thanks

**Comment by ffoodd** [comment]
I don't know why, but no, it's not due to Bootstrap.
[Their compiled CSS have units remaining after zero values](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L3788).
 [Yours does too](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v4-dev/dist/css/boosted.css#L5067), even if it's pretty strange: IE11 doesn't seem to appreciate `0px` value and prefer percent.

Maybe this is somewhat a recent fix in Bootstrap, but their version just works with IE11.

**Comment by ygatesoupe** [comment]
According to this [doc](https://msdn.microsoft.com/en-us/library/dn254946%28v=vs.85%29.aspx)  "-ms-" prefixed is not supported on Edge so flex-basis: 0% is used.

Maybe the issue comes from your scss compiler not preserving units on 0 values ?

**Comment by ffoodd** [comment]
I'm talking about IE11, not Edge :)
But I'll double-check my project's compiler, you're right!

**Comment by ygatesoupe** [comment]
Any news on this one ?

**Comment by ffoodd** [comment]
Oh yes, sorry! 

This was indeed due to a part of compilation, I close this!
