### ISSUE TITLE
$breadcrumb-font-family is not !default

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#63]
This is especially annoying when customizing the icon font, even while following the orange icons' project's README (which tells to use project's name as icon-font name).

Although I perfectly understand the need to lock many other variables, this specific one shouldn't be locked.

**Comment by ygatesoupe** [comment]
Hello,

This is fixed in commit 07a0d157ec25d

Everything now is !default, yay !
