### ISSUE TITLE
Orange Helvetica missing in dist folder in 5.0.0-beta2

### ISSUE THREAD

**Issue by vogloblinsky** [Orange-OpenSource/Orange-Boosted-Bootstrap#652]
Environment :

- macOS 11.2.3
- Node.js 14.16.0

Workflow :

- npm i --save boosted@next
- in dist folder, i only have css and js folders.

In the v5-dev branch, in the dist folder, fonts folder is present, but seems created for v5.0.0-beta.1

**Comment by ffoodd** [comment]
It's been fixed in [f26a859](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/f26a859527af5576a9eea5d2d0ac76955bdb97b5) and should be effective in beta3 release.

**Comment by ffoodd** [comment]
Please do not add labels and set a milestone or project by yourself, BTW, this is for Boosted team management.
