### ISSUE TITLE
[BUG] o-footer nav-link padding-left

### ISSUE THREAD

**Issue by vogloblinsky** [Orange-OpenSource/Orange-Boosted-Bootstrap#655]
![image](https://user-images.githubusercontent.com/2841805/115721190-18126e80-a37e-11eb-8a42-10d2b94a6e8f.png)

Just got this on o-footer nav-link?

Is it a bug or a feature ?

Code : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v4-dev/scss/_o-footer.scss#L23

**Comment by Lausselloic** [comment]
Hello,

I think it's a feature to have link left align when displaying on multiple line, if padding is divided in two and set on left and right of footer navlink it will be display as following : 
![image](https://user-images.githubusercontent.com/11272238/116372524-c26e1400-a80c-11eb-9ae5-5a0dbca74e10.png)

So I think actual display is a feature
![image](https://user-images.githubusercontent.com/11272238/116372152-6efbc600-a80c-11eb-9e50-7409b17461ee.png)

If you've a better idea to set link in the middle of clicable area AND left aligned when displayed on multiple line let me know

**Comment by ffoodd** [comment]
Could be avoided using a negative margin, instead of resetting the left padding?

**Comment by Lausselloic** [comment]
Just give it a try and it's a good idea (as usual)

- put back `.875rem` of padding left and right
- set a negative left margin to `-.875rem`
