### ISSUE TITLE
Accordion component issue ?

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#656]
Hi
We noticed that the component accordion seem to have a padding with negative margin but value seem to be too high (0.875rem rather than 0.75rem) so text could get out of the component.
Normally it should not be seen, but in our integration as we used a div with the property overflow:hidden, everything that get out of the component is truncated

![image](https://user-images.githubusercontent.com/63303383/116117240-4a90d400-a6bc-11eb-8f14-ff40c3bbe98e.png)

Could you please provide us a feedback on it ?

**Comment by Lausselloic** [comment]
Hello @MathieuPomm you're right there a mistake between padding and marin value due to https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/6d6df396293b467417ebc7ed27609a7a3e949d9c I'll make a fix and create a PR
