### ISSUE TITLE
Dropdown items - Dark background

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#657]
- Operating system: macOS
- Browsers: Firefox and Chrome

This bug is directly viewable in https://boosted.orange.com/docs/4.6/components/dropdowns/#dark-background.
The dropdown items are written in white on a white background; and so become invisible except while hovering them.
This is maybe a duplicate but I haven't found another reference to it.

![2021-04-27 13 51 03](https://user-images.githubusercontent.com/17381666/116236728-b1b39480-a75f-11eb-99d4-c36784bf621c.gif)

**Comment by Lausselloic** [comment]
On dark background, dropdown menu need also to have dark background 
![image](https://user-images.githubusercontent.com/11272238/116257765-9dc65d80-a774-11eb-9696-29b6f461d9a0.png)
