### ISSUE TITLE
[DOC] Sass - add custom boosted Sass-variables to documentation

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#661]
Following Bootstrap improvement : https://github.com/twbs/bootstrap/commit/4c7a3e8adf73bf55a5fba5905b356468be17bc0e
As pointed out by @julien-deramond 
```
adds Sass docs (variables, mixins, and loops) to most pages. Some of them specific to Boosted aren't they missing? I'm thinking about @each $name in map-keys($btn-social-networks) { in _button.scss for example.
```

- [ ] List custom boosted sass vars candidate
- [ ] Add relevant ones to documentation

**Comment by julien-deramond** [comment]
Closing it. We've done it in one of the v5.x in the whole documentation to ensure consistency.
