### ISSUE TITLE
Dependency on the vulnerable package "Swiper 4.5.1"

### ISSUE THREAD

**Issue by FulgerX2007** [Orange-OpenSource/Orange-Boosted-Bootstrap#669]
Boosted version 4.6.0 depend on the vulnerable package [Swiper  ](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/564dce695a469841decbf7728ad32f1f94ea7cdd/package.json#L99) (https://www.npmjs.com/advisories/1694)

**Comment by ffoodd** [comment]
Shouldn't this be closed now, after [38449b9a](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/38449b9a0cc49a9926952ed02a2e35e718154e72)?
