### ISSUE TITLE
Default icons

### ISSUE THREAD

**Issue by Orhleil** [Orange-OpenSource/Orange-Boosted-Bootstrap#68]
Hello,

As I was searching for a new icon in Boosted, I noticed that [the docs mention that no icon library is included by default](http://boosted.orange.com/4.0/docs/4.0/extend/icons/#content). However in the latest  NPM package (4.0.0-beta.1), there is a provided icon library.
Is this icon library going to be removed, or are the docs wrong ?

Thanks in advance for your answer.

**Comment by Lausselloic** [comment]
Hello,

Yes this icon library is going to be removed, as thos icons are Orange property, and could be found on internal websites. These library doesn't evolve anymore, and the generated font-file is there only for backwrad compatibility. If you work for an Orange project, you can use it, but if not, don't used it as explain in notice file : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v4-dev/NOTICE.txt
