### ISSUE TITLE
404 page not displayed correctly since v5

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#683]
404 page is not displayed correctly since v5.0.0 as you can see in https://boosted.orange.com/abcde (after a refresh)

![Capture d’écran 2021-06-08 à 08 18 11](https://user-images.githubusercontent.com/17381666/121132994-1c152580-c832-11eb-8208-3435f35ea003.png)

**Comment by Lausselloic** [comment]
looks like it's fixed in PR #680 let's check after 5.0.1 was released
