### ISSUE TITLE
Use Fathom Analytics

### ISSUE THREAD

**Issue by Nurovek** [Orange-OpenSource/Orange-Boosted-Bootstrap#684]
As Bootstrap uses it, it could be nice to have some tool to get analytics. Therefore they [use Fathom Analytics](https://usefathom.com/).

We need to check what it takes (pricing plans/account/users...) and if it is useful for us to have this kind of tool.

**Comment by Lausselloic** [comment]
We already use Google Analytics for user that accept tracking with Tarteaucitron https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v5-dev/site/assets/js/tac.js
