### ISSUE TITLE
Mention full jQuery version in "Getting started" for apps that use Ajax calls

### ISSUE THREAD

**Issue by PierreQuentel** [Orange-OpenSource/Orange-Boosted-Bootstrap#69]
I am starting to migrate an application to Boosted 4.

The documentation uses the jQuery "slim" version. I tried that and got an error because `$.ajax` is not supported by this version.

The "Getting started" version says that _While we use jQuery’s slim build in our docs, the full version is also supported_ ; could you add a line saying that applications that use Ajax calls should use the full version, and provide the link with the correct `integrity` attribute ?

**Comment by Johann-S** [comment]
Maybe it can help you :wink: 

```
<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" crossorigin="anonymous"></script>
```
to generate the `integrity` value use : https://www.srihash.org/

**Comment by PierreQuentel** [comment]
Thank you. Can this be added to the documentation ? If so, should I submit a PR ?

**Comment by Johann-S** [comment]
@Lausselloic any concerns about adding that to your documentation ?

**Comment by Lausselloic** [comment]
Yes, we will take a look to put a warning into the doc, and more details about Slim version versus full one.
@Johann-S Maybe also an improvement for Bootstrap doc? Will see to PR that when we've done

**Comment by Johann-S** [comment]
Yep that's can be an improvement in Bootstraps documentation :+1: 

What jQuery said about that slim version : 

>Sometimes you don’t need ajax, or you prefer to use one of the many standalone libraries that focus on ajax requests. And often it is simpler to use a combination of CSS and class manipulation for all your web animations. Along with the regular version of jQuery that includes the ajax and effects modules, we’ve released a “slim” version that excludes these modules.
