### ISSUE TITLE
Dropdown closes when I click on the scrollbar (IE8/11)

### ISSUE THREAD

**Issue by mickaelroupie** [Orange-OpenSource/Orange-Boosted-Bootstrap#7]
Two bugs are detected with boost 3.0.2 and boosted 3.3.0 for dropdowns.

We use a dropdown with many items. We defined a height for the "ul" tag. Thus, a scrollbar is used. 

Issues :
- The focus is still set on the first element and hover element instead of only being set on the hover element. (Usual behavior Bootstrap dropdowns and traditional select boxes) (IE, Chrome - not tested on Firefox)
![2016-09-07_10h10_29](https://cloud.githubusercontent.com/assets/15240533/18304576/535cdca6-74e3-11e6-939c-447d82942ca3.png)

- The dropdown is closed when a click is done on a scollbar (IE only)
No issue when we use the mouse wheel. I guess there is a loss focus problem for this bug when we click on the scrollbar on IE as shawn on the image below
![2016-09-07_10h15_15](https://cloud.githubusercontent.com/assets/15240533/18304663/faaae750-74e3-11e6-9fcc-bd9e083bf2ca.png)

Could you please quickly provide us a solution for these two bugs?

Thank you.

**Comment by ygatesoupe** [comment]
Issue 1 fixed in commit [2b8bbc4](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/2b8bbc4830e005ad5e9aee877a18b16bcff86807)

Issue 2 fixed in commit [9befc8a](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/9befc8ad54ab38b27d5abb4b7214d8c7e3340ff6)

**Comment by mickaelroupie** [comment]
Thank you. I will test it :)
