### ISSUE TITLE
Bad syntax in the orangeIcons.min.css due to svg-buy mixin

### ISSUE THREAD

**Issue by dreameddeath** [Orange-OpenSource/Orange-Boosted-Bootstrap#70]
Version : 4.0.0-beta.1

## Issue
Wrong "\a" in the svg-buy class for backgroup-image property in orangeIcons.css / orangeIcons.min.css

## Context
During the integration of orange boosted 4.0.0-beta.1 in an angular app, the build for production failed during the extract-css phase due to a bad syntax in orangeIcons.min.css (a "\a" in the svg-buy class for background-image).

Indeed the generated bundled css wasn't loaded properly as during the bundled phase the "\a" is replaced by a carriage-return

## Analysis
After investigation, it iss
Indeed the mixin scss/mixins/_orangeIcons.scss contains a bad "\n" for the svg-buy mixing

**Comment by Lausselloic** [comment]
Hello, 

We don't really maintain OrangeIcons at time, but will take a look at it.
Did you try to use http://ng-boosted.orange.com for your Angular app instead of Boosted which is based on Jquery?

**Comment by Lausselloic** [comment]
Problem solved in boosted v4.0.0-beta.2
Thanks for this catch-up
