### ISSUE TITLE
Buttons behavior on dark background

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#713]
In v4.6 we had a "dark backgrounds" indication for the behavior of the primary, secondary etc. buttons. : https://boosted.orange.com/docs/4.6/components/buttons/
However in v5, there does not seem to be this type of indication anymore (https://boosted.orange.com/docs/5.0/components/buttons/#examples)

We understand that the behavior is supposed to be the same as v4.6 ... but do you have any details that we could share with our developers on this subject?

Our use case is: a user hovers over a tile containing text and buttons.
The "original" tile is with a white background, black text: on hover, it should become with a black background and white text / button evolution / etc. to accentuate the contrast.
Is that correct ?

**Comment by julien-deramond** [comment]
I don't have the complete history but others will complete my answer.

> In v4.6 we had a "dark backgrounds" indication for the behavior of the primary, secondary etc. buttons. : https://boosted.orange.com/docs/4.6/components/buttons/
However in v5, there does not seem to be this type of indication anymore (https://boosted.orange.com/docs/5.0/components/buttons/#examples)

Yes you're right. We have [dark background for buttons in v4.6](https://boosted.orange.com/docs/4.6/components/buttons/#dark-backgrounds) and not yet in v5.
Currently, the v5 is "just" a basic customization of the Bootstrap v5 to match Orange brand and we're working on developing the custom Orange components in the v5 that were in the v4: global headers, etc.
Bootstrap doesn't handle yet dark backgrounds. So it was specific to Orange in the v4.6.
Your question is linked to https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/117 that is in study for the v5: do we stick with what we did in v4.6 for the buttons (`.btn-inverse` class) or do we develop a complete dark mode system?

> We understand that the behavior is supposed to be the same as v4.6 ... but do you have any details that we could share with our developers on this subject?

Indeed, the behavior is supposed to be the same as v4.6:

![Capture d’écran 2021-06-25 à 06 39 07](https://user-images.githubusercontent.com/17381666/123370529-2fd5c100-d580-11eb-9a8e-a23b04b3da85.png)

> Our use case is: a user hovers over a tile containing text and buttons.
The "original" tile is with a white background, black text: on hover, it should become with a black background and white text / button evolution / etc. to accentuate the contrast.
Is that correct ?

From what I understrand, it seems correct.
I'm thinking about 2 approaches for this:

1. You could find another way to accentuate the contrast without using a dark mode. Maybe by adding some thick borders while hovering the tile (or something else) so you'll won't need the dark mode; but your designers should agree with that.
2. You could temporary create a `.btn-inverse` class (and some CSS rules) associated with a dark background (`.bg-dark`) as it was done in v4.6 by waiting there is a solution in the v5. When there'll be a solution in v5, you would be able to migrate to it by removing your custom `.btn-inverse` class.

**Comment by ffoodd** [comment]
You're right. v5 is able to use CSS custom properties, which should ease adding dark mode variants a lot—but that's a whole topic on its own.

FYI every components should have a dark background variants, not only buttons: that's why the v4 approach is probably not viable anymore. Components need to be aware of their context, without requiring an extra class for each component instance.

**Comment by MathieuPomm** [comment]
Thank you for your feedbacks.
I think our use-case is different from complete dark mode (eg from my understanding : a whole page with white background might become dark background if some option is chosen by the end-user in its browser for example), which I think is a entire topic.
I was referring to some "blocks" of content that might be with a black background and about the behavior of buttons regarding those blocks.
For example, OCI (https://www.orange.ci/) use a carousel on its homepage with a black background.
![image](https://user-images.githubusercontent.com/63303383/123382265-058cff00-d592-11eb-9010-cdaeaddebce7.png)

What I understand is : we should create temporarily  the `.btn-inverse class` as mentioned above in your solution 2. And then v5 will probably address the dark background variant for every component (in the future). Is that correct ?

thanks again for your comments !

**Comment by julien-deramond** [comment]
> I think our use-case is different from complete dark mode (eg from my understanding : a whole page with white background might become dark background if some option is chosen by the end-user in its browser for example), which I think is a entire topic.
I was referring to some "blocks" of content that might be with a black background and about the behavior of buttons regarding those blocks.

Your case is indeed different from a complete dark mode. It is more contextual, you would rather like to say that the content of this part of the website (or this or that component) is in "color inverted" mode.

> What I understand is : we should create temporarily the `.btn-inverse` class as mentioned above in your solution 2. And then v5 will probably address the dark background variant for every component (in the future). Is that correct ?

Yes, you could reintegrate temporarily in your project the `.btn-inverse` class (see https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v4-dev/scss/_buttons.scss) as long as there is no dark background variant in the v5. And v5 will address this subject in a near future.

**Comment by ffoodd** [comment]
FWIW a complete dark mode is not what I meant, it has no value at all regarding Orange brand.

However handling dark variants if each components the same way (using custom properties) is the only safe way forward. Adding classes to each component is not easy enough, so things like `.btn-inverse` cannot work on complex components or pages.

But setting a single class like `.dark-mode` (or whatever) on a container (say your carousel section) and overriding a few custom properties that would cascade back to each components inside would make using dark variants a breathe.

**Comment by MathieuPomm** [comment]
Thank you @ffoodd & @julien-deramond for your feedbacks.
Will share your inputs with our developers. 
Have a nice week-end !

**Comment by philparry** [comment]
Please refer to the following page (scroll down) and you will see an example where button needs to be transparent, so that inherits the correct background colour, which is #333 and nor #000

https://design.orange.com/articles/accessible_advertising_trailers/
