### ISSUE TITLE
Docs: Clicking on social buttons redirects to the main page

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#733]
Clicking on social buttons redirects to the main page in the [v5 documentation](https://boosted.orange.com/docs/5.0/components/buttons/#social-buttons).

This was not the case in the [v4 documentation](https://boosted.orange.com/docs/4.6/components/buttons/#social-buttons) and is not the case in the v5 documentation for other buttons in the same page.

**Comment by ckkeppler** [comment]
> Clicking on social buttons redirects to the main page in the [v5 documentation](https://boosted.orange.com/docs/5.0/components/buttons/#social-buttons).
> 
> This was not the case in the [v4 documentation](https://boosted.orange.com/docs/4.6/components/buttons/#social-buttons) and is not the case in the v5 documentation for other buttons in the same page.

I would like to contribute but cannot seem to gain access to v5 code when cloning.  I am new to contributing but would like to help.  Can you tell me how to access v5 code?

**Comment by julien-deramond** [comment]
Welcome @ckkeppler!
> Can you tell me how to access v5 code? 

Our default branch is still `v4-dev` (version 4). You can checkout the `v5-dev` to access to the version 5 (current version).
