### ISSUE TITLE
table hover sometime border not appear after hovering

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#739]
On Edge Chromium W10
https://boosted.orange.com/docs/5.0/content/tables/#hoverable-rows after hovering quickly multiple times the row, some border are hidden
![image](https://user-images.githubusercontent.com/11272238/126129783-0047a670-903f-497a-918a-db6ab39e07de.png)

Maybe linked to no table accent bg mentionned in boosted : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v5-dev/scss/_tables.scss#L7

But used here : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v5-dev/scss/_tables.scss#L98

In boosted we have set border on `TR` and define a `line-height` on each cells maybe this conflict with the way bootstrap manage variant: https://boosted.orange.com/docs/5.0/content/tables/#how-do-the-variants-and-accented-tables-work ?

**Comment by julien-deramond** [comment]
Reintegrating `*table-accent-bg` doesn't fix anything just like that but I think it would be nice to fix it anyway to stay the closest possible to Bootstrap:
```diff
diff --git a/scss/_tables.scss b/scss/_tables.scss
index a3513b44a..b53ca9413 100644
--- a/scss/_tables.scss
+++ b/scss/_tables.scss
@@ -4,7 +4,7 @@

 .table {
   --#{$variable-prefix}table-bg: #{$table-bg};
-  // Boosted mod: no table-accent-bg
+  --#{$variable-prefix}table-accent-bg: #{$table-accent-bg};
   --#{$variable-prefix}table-active-color: #{$table-active-color};
   --#{$variable-prefix}table-active-bg: #{$table-active-bg};
   --#{$variable-prefix}table-hover-color: #{$table-hover-color};
diff --git a/scss/_variables.scss b/scss/_variables.scss
index 80614b652..eb6f21092 100644
--- a/scss/_variables.scss
+++ b/scss/_variables.scss
@@ -646,7 +646,7 @@ $table-line-height:           1.25 !default; // Boosted mod

 $table-color:                 $body-color !default;
 $table-bg:                    $body-bg !default;
-// Boosted mod: no $table-accent-bg
+$table-accent-bg:             $body-bg !default;

 $table-th-font-weight:        null !default;

diff --git a/scss/mixins/_table-variants.scss b/scss/mixins/_table-variants.scss
index 9fc3b423b..bdfe0e553 100644
--- a/scss/mixins/_table-variants.scss
+++ b/scss/mixins/_table-variants.scss
@@ -6,6 +6,7 @@
     $active-bg: mix($color, $background, percentage($table-active-bg-factor));

     --#{$variable-prefix}table-bg: #{$background};
+    --#{$variable-prefix}table-accent-bg: #{$background};
     --#{$variable-prefix}table-active-bg: #{$active-bg};
     --#{$variable-prefix}table-active-color: #{color-contrast($active-bg)};
     --#{$variable-prefix}table-hover-bg: #{$hover-bg};
```

**Comment by MewenLeHo** [comment]
@Lausselloic: Is this bug still relevant? We were unable to replicate it.

**Comment by Lausselloic** [comment]
I can't reproduce, maybe a browser bug
