### ISSUE TITLE
[Feature] Configurable Megamenu

### ISSUE THREAD

**Issue by GregoCo** [Orange-OpenSource/Orange-Boosted-Bootstrap#76]
Could we imagine a light alternative to the dark panel content ? 

We made tests with users in their environment and they said "With our lights, and brillant screens, we have reflect and it is really hard to read content menu."

Thanks in advance

--
[French] Peut-on imaginer une alternative claire au contenu du megamenu ? 

Nous avons fait des tests utilisateurs en condition et ils nous ont dit qu'avec leur lumière (Spot) et leur écran brillant, il était difficile de lire le contenu du menu.

D'avance merci.

**Comment by ygatesoupe** [comment]
Hello,

Light background on megamenu or navbar is not currently supported by Orange Brand Guidlines, so you won't find this option in related boosted components.
You may contact orange branding support and submit your issue.
