### ISSUE TITLE
Use Helvetica Now

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#774]
Use Helvetica Now in Boosted v5
- [x] **Waiting for** information from Monotype after first technical feedbacks
- [ ] Get in touch with [orange.com](https://www.orange.com/fr) (or directly in the browser) to analyze their implementation
- [x] Analyze the [ongoing @ffoodd PR #640](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/640)
- [x] Evaluate the complexity of using Helvetica Now in Boosted v5
- [x] Evaluate the complexity of using Helvetica Now in Boosted v4

**Comment by ffoodd** [comment]
One of my latest PR added new examples, two of which were the same article template using Helvetica Neue / Now to compare 🙂
