### ISSUE TITLE
Portrait videos

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#775]
- [x] Study how to display portrait videos
- [x] #907
- [x] #909

**Comment by MewenLeHo** [comment]
@julien-deramond: I made a CodePen with a custom 9/16 ratio (9/16 ratio is the ratio for portrait video made by a smartphone) : [https://codepen.io/MewenLeHo/pen/JjyMKYY](https://codepen.io/MewenLeHo/pen/JjyMKYY)
Is it what you wanted?[](url)

**Comment by julien-deramond** [comment]
Some users asked for the possibility to display videos in portrait mode yes. @CyriaqueBillard do you think this CodePen corresponds to what the users asked for few months ago?
