### ISSUE TITLE
docs - update screenshots

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#79]
Sample page documentation screenshots need to be updated. 

- best idea : found a tool to take screenshot as it was on boosted 3
- no so bad : generate it manually

**Comment by ygatesoupe** [comment]
Solution proposed in commit  f5e9885

Unfortunately phantomjs doesn't render correctly flex based layout.

Another option is to take a look at Chrome Headless and this Node API which sounds promizing https://github.com/GoogleChrome/puppeteer
