### ISSUE TITLE
sass - add explicit dependency to sass-math-pow

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#80]
For yiq Boosted function, we use a pow function in JS , need to replace it by an explicit sass dependency to allow sass build outside NodeJS
https://www.npmjs.com/package/sass-math-pow

**Comment by Lausselloic** [comment]
fixed by commit 15599a02b0203ebf5aadf33e50d061fc4e201809 add an explicit dependency

**Comment by PriscaMoine** [comment]
Hello, 
can you teal me when this hot fix release is planned ? 
thank you in advance, 
Prisca

**Comment by Lausselloic** [comment]
Hello,

Soon soon soon, we're merging Bootstrap V4 official release.... So today or tomorrow you will have the boosted 4.0 stable release including this hotfix
