### ISSUE TITLE
Navbars Orange : change the color of the 1px border-bottom

### ISSUE THREAD

**Issue by Nurovek** [Orange-OpenSource/Orange-Boosted-Bootstrap#804]
Currently in the v4, the 1px border-bottom has the color `#333`
https://boosted.orange.com/docs/4.6/components/navbar-orange/

However, in the Zeplin designs for headers says that this thin line has the color `#666`, as you can see below

![image](https://user-images.githubusercontent.com/5867791/133763138-fb5f5d59-73e2-429c-9f41-27409e25d178.png)

**Comment by Hariomsingh333** [comment]
can i do this work.

**Comment by Hariomsingh333** [comment]
i want to fix the problem, can i do this

**Comment by julien-deramond** [comment]
> i want to fix the problem, can i do this

Thank you for your proposal @Hariomsingh333 but we keep this one to onboard a new member in our core team ;)

**Comment by Hariomsingh333** [comment]
ok that great
