### ISSUE TITLE
Percy usage notification for Orange

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#816]
We received the following notification:

> Percy notification for Orange
>
> You have used all the snapshots included in your free plan
> You can review existing builds, but no new snapshots wil be processed until your next billing cycle starts.
> To continue using Percy this month, upgrade your account.

Study if we should:
* Upgrade our account / Pay
* Limit the type of actions that triggers Percy
* Make the trigger manual

Our current plan includes 5000 screenshots/month

**Comment by ffoodd** [comment]
I added a `skip:ci` label intended to prevent some actions to run for every PR, but it requires to add the said label when opening PR.

Can probably be improved 😉

**Comment by julien-deramond** [comment]
> I added a `skip:ci` label intended to prevent some actions to run for every PR, but it requires to add the said label when opening PR.
> 
> Can probably be improved 😉

You even created a `skip:percy`. Don't know if it is possible, but maybe it could be set by default for each PR.

**Comment by julien-deramond** [comment]
Tried a different approach with https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1004. If considered sufficient, close this PR.
