### ISSUE TITLE
Popper t is indefined

### ISSUE THREAD

**Issue by danygit** [Orange-OpenSource/Orange-Boosted-Bootstrap#82]
I'm using the new version of boosted.
When i click to a dropdown, i have the error in console and dropdown item dont appear.

If i replace :
<script src="https://.../js/compiled/boosted.min.js"></script>
By
<script src="https://getbootstrap.com/dist/js/bootstrap.js"></script>

The dropdown works.

**Comment by Lausselloic** [comment]
Bug reports must include a live demo of the problem. Per our
[contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v4-dev/.github/CONTRIBUTING.md) , please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Boosted version, and specific browser and OS details.

**Comment by danygit** [comment]
When i comment this next line, the dropdown works : 

 // Boosted mod
  .on('DOMContentLoaded', function () {
    // Instanciate every dropdown in the DOM
    Dropdown._jQueryInterface.call($$$1(Selector.DATA_TOGGLE), 'init');
  }); // end mod

**Comment by ygatesoupe** [comment]
Hello,

Can you provide the exact html markup you are using for dropdowns, and since you mention an error logged in the console it might help to share it with us as well.

Thanks

**Comment by danygit** [comment]
The HTML code =

<div id="language-switcher" class="language-switcher" style="">
  <button type="button" id="btn-lang" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="changer la langue du site" data-target="#extra-languages" aria-haspopup="true">
    <span class="current">fr</span>
  </button>
  <ul id="extra-languages" class="dropdown-menu" role="menu">
    <li role="menuitem">
      <a hreflang="en" aria-label="english version" href="/en/home">en</a>
    </li>
  </ul>
</div>

**Comment by ygatesoupe** [comment]
You might want to try the following htm in your environement

```html
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
```
and see if it works any better.

As you have probably read in the [migration guide](http://boosted.orange.com/docs/4.0/migration/#dropdowns) dropdown component has had a few changes since last release.
As you can see on the example above, `data-target`attribute is gone, and dropdown items now require `.dropdown-item`class.

**Comment by danygit** [comment]
I read the "migration guide" and I had already made the changes in the code but i revert.
I continue to investigate

**Comment by danygit** [comment]
You could close this ticket. I dont have the solution but i think the problem is my environment build that not work with the new version of boosted.
