### ISSUE TITLE
custom-checkboxes not visible whith high contrast on windows

### ISSUE THREAD

**Issue by Lausselloic** [Orange-OpenSource/Orange-Boosted-Bootstrap#87]
Hello, in our project, we use custom checkboxes and radio buttons using the custom-checkbox and custom-radio classes. When switching to "High Contrast" mode in Windows, as shown in the screen below:
![themes](https://user-images.githubusercontent.com/11272238/42622908-ca0231da-85c1-11e8-9837-f31973896cbc.PNG) 

Extract of Forms · Boosted
![checkboxandradioscontraste](https://user-images.githubusercontent.com/11272238/42622954-e29d4a68-85c1-11e8-9ab4-e704b279c589.PNG)

**Comment by notabene** [comment]
Quoting @patrickhlauke from Twitter, for future reference:

https://twitter.com/patrick_h_lauke/status/1017696116182343680
> for modern IE/Edge, and just to check WHCM, i'd use a JS-based media query check https://codepen.io/patrickhlauke/full/woEdjx (made that ages ago for https://developer.paciellogroup.com/blog/2016/12/windows-high-contrast-mode-the-limited-utility-of-ms-high-contrast/)

https://twitter.com/patrick_h_lauke/status/1017696405836746752
> or, of course, just add CSS specific to that media query check - no JS needed

**Comment by liyokuna** [comment]
thanks @notabene 
it will help to resolve that issue.
i am sharing also this one :[http://www.gwhitworth.com/blog/2017/04/how-to-use-ms-high-contrast](on the use of ms contrast)

**Comment by liyokuna** [comment]
I solve by editing the CSS classes used for checkboxes and radio button. Classes using attributes `:before` and `:after`.
I post  #this [issue](https://github.com/twbs/bootstrap/issues/26892) on bootstrap's github but id didn't have an answer.

**Comment by notabene** [comment]
@liyokuna can you show us the solution you found?

**Comment by liyokuna** [comment]
sorry !
![checkboxes](https://user-images.githubusercontent.com/11217936/42954408-ea5cd53c-8b7c-11e8-8642-efffd3ea4989.PNG)
i did test with the 4 others contrast mode.

**Comment by notabene** [comment]
YES! Good job!

**Comment by parrysan** [comment]
Nice! 

Phil Parry
+44 7866 889 063

**Comment by Lausselloic** [comment]
For thos who wants to review the source code : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commits/issue87_on_custom_checkboxes

**Comment by notabene** [comment]
@parrysan actually we're discussing it internally, it's not solid enough for now (but a good step in the right direction); it only works for IE so far.

**Comment by liyokuna** [comment]
https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/e96908769822c9900bc22799c192452e69b4b181
