### ISSUE TITLE
Local Headers > Title Bar

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#889]
## References

- **Orange Design System**: [Modules > Local Headers](https://system.design.orange.com/0c1af118d/p/774477-local-headers/b/743cd0):
  * Title Bar On White - WEB-LOC-TIB-001
  * Title Bar On black - WEB-LOC-TIB-002
  * Title Bar With Illustration - WEB-LOC-TIB-003WEB-GLH-STN-001

## More info

Two cents from @ffoodd:

Should probably not be a component, only a `.display-*` heading with a `.bg-*` container:

```html
<div class="bg-dark">
   <h1 class="display-0">Title</h1>
</div>
```

To handle the illustration, several options:
1. a `background-image`, meaning it's a per-project customization (but we should provide an example)
2. a `<img>` tag, with some nuances for art direction — using `srcset` and `sizes` when using bitmap images (e.g. JPG or PNG, you got an example on "Examples" list), or scoped CSS if using a SVG (like in `orange-logo.svg`).

Number 2. is my preferred one, an I think we should provide an example of both bitmap and SVG images.

- Examples for Title bar, maybe only in /examples?
  - Maybe provide bitmap/SVG implementations in "Content" / "Images" too, in the docs?

**Comment by louismaximepiton** [comment]
WIP on this [CodePen example](https://codepen.io/louismaximepiton/pen/wvqaJOE?editors=1100).
