### ISSUE TITLE
Need to override pagination next/previous link border

### ISSUE THREAD

**Issue by Handja** [Orange-OpenSource/Orange-Boosted-Bootstrap#89]
I want to override pagination variable 'cause my project need inverse colors.

But in _pagination.scss, the border-color attribute is set to $black and i can't override this variable.
I need a dedicated var like $pagination-border-color.

```
  &:last-child {
    .page-link {
      @include border-right-radius($border-radius);
      // Boosted mod
      border-color: $black;
      ...
```

**Comment by Lausselloic** [comment]
Hello,

Just take a look on it, and yes we need to use a variable for that. When you say inverse color, if we set the border-color=text-color does it fit to your need? Or you need to have 3 different colors? One for text, one for background and a different one for border?

**Comment by Handja** [comment]
Ng bosted purpose this component
![pagination_light](https://user-images.githubusercontent.com/9036576/43569805-e24e1218-9638-11e8-98a1-2673b0711817.png)

I need this 
![pagination_dark](https://user-images.githubusercontent.com/9036576/43570588-fd7fbabc-963a-11e8-8b6b-ba5dc1ad4f68.png)

Same things for Toggle
![toggle_dark](https://user-images.githubusercontent.com/9036576/43570634-1e02fbdc-963b-11e8-8473-8502cacde55a.png)


I think **border-color=text-color** can work for my case.
