### ISSUE TITLE
Local Headers > Local Navigation

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#890]
## References

- **Orange Design System**: [Modules > Local Headers](https://system.design.orange.com/0c1af118d/p/774477-local-headers/b/743cd0):
  * Local navigation on white - WEB-LOC-NAV-001
  * Local navigation on black - WEB-LOC-NAV-002
* It kind of replaces v4 Priority Nav: https://boosted.orange.com/docs/4.5/components/priority-nav/

## More info

Two cents from @ffoodd:

This pattern could be done in three ways:
1. nav component, followed by a collapse component: mutually exclusive depending on breakpoint, meaning e.g. if collapse should be displayed until `lg` breakpoint, nav should be `d-none d-lg-block`. This would require to double the markup or so, and to heavily rely on utilities to stick to Web UI Kit look and feel.
2. nav component with `.navbar-collapse` and `.navbar-expand-*`, and a `nav-toggler` variant to handle color, arrow and full-width aspect (see https://v5-dev--boosted.netlify.app/docs/5.0/components/navbar/#responsive-behaviors).
3. creating a new component to handle the behavior with JavaScript. This would lead to another question: should the breakpoint to switch to a collapse be defined manually or computed by the component?

I'd go with 2. since it doesn't require much dev, only to add a `.navbar-toggler` variant and rely on existing component and behavior.

- Create a `.navbar-toggler` variant:
  - Document it in "'Components" / "Nav"
  - Add it to Examples?

**Comment by louismaximepiton** [comment]
Questions about this component:

- Should it open like a dropdown or like a collapse ? Be absolute or static ?
- Do we isolate it in the documentation for bundle size/maintenance purpose ? Or do we pack it with other navs ?
