### ISSUE TITLE
Hide the Bootstrap examples

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-Boosted-Bootstrap#920]
Hide the [examples](https://boosted.orange.com/docs/5.1/examples/) from Bootstrap not yet adapted for Orange. It can create misusages from the developers using Boosted.
- Choose the examples to keep (e.g. https://boosted.orange.com/docs/5.1/examples/grid/) and those to hide
- Hide the examples with maybe a callout to inform the users?
- Create an issue to reintegrate the examples with sub-issues and a "on hold" + "brand" label

**Note**: the examples must remains downloadable!

**Comment by louismaximepiton** [comment]
Filled #410 with all the removed examples that should come again in Boosted.
