### ISSUE TITLE
Forms: red border is gone and type incorrect for input error

### ISSUE THREAD

**Issue by ygatesoupe** [Orange-OpenSource/Orange-Boosted-Bootstrap#93]
In v4.1.3 I don't see them anymore in boostwatch page : https://boosted.orange.com/docs/4.1/boostwatch/#forms

![error border](https://user-images.githubusercontent.com/15139360/45698995-9a54a980-bb69-11e8-8f8a-71b662b3857b.png)

But they are in component page  : https://boosted.orange.com/docs/4.1/components/forms/#validation (hit submit button in the form)
But error Label text is not 14px bold as it should be

![error border 2](https://user-images.githubusercontent.com/15139360/45699035-a7719880-bb69-11e8-8213-51ea7b5c1cb3.png)

**Comment by liyokuna** [comment]
the custom styles from [validation]( https://boosted.orange.com/docs/4.1/components/forms/#validation ) page is missing in boostwatch page, part on [forms](https://boosted.orange.com/docs/4.1/boostwatch/#forms).
v4.1.3

**Comment by liyokuna** [comment]
the custom styles from validation page is not missing in boostwatch page, part on forms.
v4.1.3.
They never be added there.

**Comment by liyokuna** [comment]
Will be added
