### ISSUE TITLE
Dropdown with search - existing button ?

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#940]
Hello

We would like to use a component (branded) as a dropdown with search and auto-completion (for example like : https://mdbootstrap.com/snippets/jquery/mdbootstrap/921549)

Does this kind of component already exists on Boosted ? If yes, where can I find documentation to share with developers ?

Our use-case is to avoid a long long list of countries in a dropdown (ex : list of countries).

Thank you for your feedback.

**Comment by louismaximepiton** [comment]
Hi Matthieu,

This kind of component is not in Boosted v5 yet, nor in Boosted v4, but we plan to introduce it in Boosted v5. You can for instance follow the [design guidelines](https://system.design.orange.com/0c1af118d/p/88ab5b-forms/b/599459/i/66611047) (WEB-FOR-CCS-001, WEB-FOR-DDL-002 and 005). As there's no release date at the moment, a CodePen project can be offered to help developers.

Can you tell us which version of Boosted you are using ?

**Comment by MathieuPomm** [comment]
Hi Louis Maxime
thanks for your quick feedback.
Some of our portals are using Boosted v4.4 and some others v4.5.2.
An homogenization is in progress in order to upgrade all portals to Boosted v5. in January.
I'll take notes from design guidelines and will mention topic with XDLabs.
Please do not hesitate if you could share ressources (Ideally, it should be compatible with latest Boosted version as we are targetting to be aligned with latest versions).

**Comment by julien-deramond** [comment]
Note: could be closed by https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/943 or https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/453

@MathieuPomm, depending on with which techno you're using Boosted, there are some solutions that could help you implementing it in the meantime coupled to the design guidelines @louismaximepiton mentioned:
* in Angular you could use for example https://ng-select.github.io/ng-select
* ng-select was inspired from https://react-select.com/home in React

**Comment by MathieuPomm** [comment]
Thanks Julien for your feedback.
I'm noting that and will share with our developers (as they are using Java, I guess React might be useful).
NB : regarding WEB-FOR-DDL-003/005, I'm thinking those use-cases are slightly different as user might do multiple selection.
NB : #453 might indeed correspond to our current need, but we will have also some cases where we want to display long list of data (ex : address fields listing districts, for a funnel in order to retrieve delivery fees).

Thanks all for your feedbacks.

**Comment by julien-deramond** [comment]
Closing it as it will be handled in the context of #943
