### ISSUE TITLE
[RTL] — Scroll up link icon is reversed

### ISSUE THREAD

**Issue by ffoodd** [Orange-OpenSource/Orange-Boosted-Bootstrap#95]
RTLCSS (which is good) automagically reverses angles in the `rotate()` function. Which makes `.o-scroll-up-icon` descending :)

I tricked it by adding to `_o-rtl.css` the `transform` again, but that seems wrong.

RTLCSS doesn't seem to have a way to disable a single line / selector / whatever…

**Comment by ffoodd** [comment]
Oh yeah, almost found the way, using [TLCSS StringMap](https://rtlcss.com/learn/usage-guide/string-map/).

**Comment by Lausselloic** [comment]
Thanks @ffoodd i've merge it, and will include it in the next release

**Comment by Lausselloic** [comment]
after testing the build i've fix like that : 
```
    /*rtl:ignore*/
    transform: rotate(90deg);
    /*rtl:ignore*/
```
see : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/51023a67038f6c7efb3df454f3a19530308508bf

**Comment by ffoodd** [comment]
I didn't find any other part that should be ignored from RTLCSS, but there might be. Nice to have this, though. Thanks for merging :)
