### ISSUE TITLE
The dropdown content in the navbar does not fit the web browser window

### ISSUE THREAD

**Issue by Teazane** [Orange-OpenSource/Orange-Boosted-Bootstrap#961]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When we create a navbar and put a dropdown button at the extreme right, the content of the dropdown button on the right of the navbar is not fitting the screen: the dropdown content is cut by the browser window border. The only solution I found is to use a dropstart.

### Reduced test cases

Code used: 
```html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse">
      <a class="navbar-brand mx-3" href="#"><img src="orangelogo.png" role="img" loading="lazy"></a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
      <ul class="navbar-nav me-auto">
          <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
          <li class="nav-item"><a href="#" class="nav-link" target="_blank">Other link</a></li>
      </ul>
      <form class="d-flex me-3" role="search" method="post" action="search" name="search">
          <div class="input-group">
              <select name="search_filter" id="search_filter" class="form-select">
                  <option value="default" selected>Filter choice</option>
                  <option value="1">Choice 1</option>
                  <option value="2">Choice 2</option>
                  <option value="3">Choice 3</option>
              </select>
              <input type="search" name="searched" id="searched" class="form-control" placeholder="Search..." aria-label="Search">
              <button type="submit" class="btn btn-primary btn-icon" id="search_button">
                  <img src="search.png" width="20" height="20">
              </button>
          </div>
      </form>
      <div class="dropdown">
          <a href="#" class="nav-link dropdown-toggle text-white" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="avatar.png" alt="mdo" width="32" height="32">
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownUser">
              <li><a class="dropdown-item" href="#">Profile</a></li>
              <li><a class="dropdown-item" href="#">Change password</a></li>
              <li><a class="dropdown-item" href="#">API</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Sign out</a></li>
          </ul>
      </div>
   </div>
</nav>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

v5.0.2

**Comment by julien-deramond** [comment]
I'm wondering if there isn't an issue with the code you provided in the **Reduced test cases**. Anyway, I've created [a CodePen](https://codepen.io/julien-deramond/pen/jOGqYwv) to try to reproduce (and propose a solution to) your issue. Is it corresponding?
If it is, it's handled with the `.dropdown-menu-end` class. There are other ways to do it depending on the cases which are references in [Dropdowns > Menu alignement](https://boosted.orange.com/docs/5.0/components/dropdowns/#menu-alignment).

**Comment by Teazane** [comment]
As I removed some of my code to simplify the case, maybe there is an error in my example code, but your "dropdown-menu-end" is working well ! Thanks !
