### ISSUE TITLE
stop automatic carousels

### ISSUE THREAD

**Issue by Aniort** [Orange-OpenSource/Orange-Boosted-Bootstrap#98]
hello,
to comply with wcag 2.1 accessibility guidelines, the carousels must have a pause button to stop slide movement. It's the only way to be accessible, be able to stop automatic motion.

**Comment by Lausselloic** [comment]
We need to work on the solution : 
- avoid changing dynamically the id of the element
- add a aria-label on the button
- made also a sample for swiper caroussel

I'd prefer to let it for next release. We are focussing on small bugfixes to release the 4.2.1

**Comment by Lausselloic** [comment]
related to PR : https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/130

**Comment by liyokuna** [comment]
[you can test it here](https://deploy-preview-130--boosted.netlify.com/docs/4.2/components/carousel/#with-controls)

**Comment by liyokuna** [comment]
@Aniort Changes can be viewed [here](https://deploy-preview-130--boosted.netlify.com/docs/4.2/components/carousel/#with-controls)
