### ISSUE TITLE
Link into carousel's slides

### ISSUE THREAD

**Issue by Aniort** [Orange-OpenSource/Orange-Boosted-Bootstrap#99]
Many projects use links (text) into carousel's slides to navigate to specific pages. We should make a functional example into carousel section to show devs the good practices for that kind of component.

**Comment by liyokuna** [comment]
Hello,

[Done ](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/fea10cf24aec8a32413689cae383c2dc773a51a8)! This feature will be available in the next release.
